### ISSUE TITLE
LightGBMError: b'Wrong size of feature_names'

### ISSUE THREAD

**Issue by ahbon123** [Microsoft/LightGBM#1065]
Hello there, when i run my dataset with lgb, following errors occur:

_Data: X_train: (314954, 76), X_test: (78739, 76)
Training on: (314954, 76)
Traceback (most recent call last):

  File "<ipython-input-24-2d3b4e222501>", line 80, in <module>
    model = lgb.train(params, train_lgb, num_boost_round=ROUNDS)

  File "C:\Users\User\Anaconda3\lib\site-packages\lightgbm\engine.py", line 213, in train
    booster._load_model_from_string(booster._save_model_to_string())

  File "C:\Users\User\Anaconda3\lib\site-packages\lightgbm\basic.py", line 1554, in _load_model_from_string
    ctypes.byref(self.handle)))

  File "C:\Users\User\Anaconda3\lib\site-packages\lightgbm\basic.py", line 48, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError())

LightGBMError: b'Wrong size of feature_names'_

Does somebody know how to deal with this issues? thanks.

**Comment by guolinke** [comment]
ping @wxchan @StrikerRUS

**Comment by StrikerRUS** [comment]
@ahbon123 Please provide reproducible example or at least the `params` and the head of `train_lgb`.

**Comment by wxchan** [comment]
@ahbon123 what's the type of X_train and X_test? and what's the value of ROUNDS?

**Comment by ahbon123** [comment]
Thanks for your reply @StrikerRUS @wxchan @guolinke. The bugs come from the features' titles. When I delete the row of titles, there is no more errors.
