### ISSUE TITLE
Requirement error when install GPU version

### ISSUE THREAD

**Issue by yananchen1989** [Microsoft/LightGBM#1289]
I want to install lightgbm of GPU version in my machine. Before installing it, I execute the command "`pip install cmake`" and there is no error after that.
Then I try install lgb like this below:
```
$pip install lightgbm --install-option=--gpu
/usr/lib/python2.7/site-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting lightgbm
  Using cached lightgbm-2.1.0.tar.gz
Requirement already satisfied: numpy in /usr/lib64/python2.7/site-packages (from lightgbm)
Requirement already satisfied: scipy in /usr/lib64/python2.7/site-packages (from lightgbm)
Requirement already satisfied: scikit-learn in /usr/lib64/python2.7/site-packages (from lightgbm)
Skipping bdist_wheel for lightgbm, due to binaries being disabled for it.
Installing collected packages: lightgbm
  Running setup.py install for lightgbm ... error
    Complete output from command /usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qn53GS/lightgbm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-MQ4b99-record/install-record.txt --single-version-externally-managed --compile --gpu:
    running install
    INFO:LightGBM:Starting to compile the library.
    INFO:LightGBM:Starting to compile with CMake.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-qn53GS/lightgbm/setup.py", line 278, in <module>
        'Topic :: Scientific/Engineering :: Artificial Intelligence'])
      File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
        dist.run_commands()
      File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-qn53GS/lightgbm/setup.py", line 204, in run
        opencl_include_dir=self.opencl_include_dir, opencl_library=self.opencl_library)
      File "/tmp/pip-build-qn53GS/lightgbm/setup.py", line 152, in compile_cpp
        silent_call(cmake_cmd, raise_error=True, error_msg='Please install CMake and all required dependencies first')
      File "/tmp/pip-build-qn53GS/lightgbm/setup.py", line 77, in silent_call
        raise Exception("\n".join((error_msg, log_notice)))
    Exception: Please install CMake and all required dependencies first
    The full version of error log was saved into /home/xuemeng.cyn/LightGBM_compilation.log

    ----------------------------------------
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-qn53GS/lightgbm/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-MQ4b99-record/install-record.txt --single-version-externally-managed --compile --gpu" failed with error code 1 in /tmp/pip-build-qn53GS/lightgbm/
```
I don't knwo what's wrong with this. How to solve it ?

**Comment by guolinke** [comment]
I think cmake isn't in pip. it is a system side package.
