### ISSUE TITLE
[python] gbm predict with pred_leaf=True parameter fail

### ISSUE THREAD

**Issue by supersush** [Microsoft/LightGBM#1334]
Hi, i use gbm.predict with pred_leaf=True parameter to get leaf info,but got ValueError: negative dimensions are not allowed.  If i change pred_leaf=False, all is well. Thank you for helping me find what is  wrong  when i using this method. 

Details info:
## Environment info
Operating System:centos7
CPU: Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz
C++/Python/R version:python2.7

## Error Message:
File "gbm_feature_generator.py", line 71, in lgb_pred
    train_leaves = gbm.predict(x_train, num_iteration=gbm.best_iteration, pred_leaf=True)
  File "/home/xx/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 1784, in predict
    return predictor.predict(data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape)
  File "/home/xx/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 437, in predict
    predict_type)
  File "/home/xx/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 491, in __pred_for_np2d
    preds = np.zeros(n_preds, dtype=np.float64)
ValueError: negative dimensions are not allowed
## Reproducible examples
params = {
        'task': 'train',
        'boosting_type': 'gbdt',
        'objective': 'binary',
        'metric': {'binary_logloss', 'auc'},
        'num_leaves': 30,
        #         'max_depth': 7,
        'num_trees': 32,
        'learning_rate': 0.05,
        'feature_fraction': 0.9,
        'bagging_fraction': 0.8,
        'bagging_freq': 5,
        'tree_learner': 'data',
        'num_threads': 10,
        'early_stopping_round': 5,
        'verbose': 0
    }

gbm = lgb.train(params,
                    lgb_train,
                    num_boost_round=100,
                    valid_sets=lgb_eval,
                    feature_name=feature_names,
                    categorical_feature=categorical_feature,
                    early_stopping_rounds=5)
train_leaves = gbm.predict(x_train, num_iteration=gbm.best_iteration, pred_leaf=True)

**Comment by guolinke** [comment]
is the error caused by this line: https://github.com/Microsoft/LightGBM/blob/ebb07f019a611ec9d3712aadbc9e725faaa9c78c/python-package/lightgbm/basic.py#L457 ?

**Comment by supersush** [comment]
according to the traceback, i think it is caused by this line
> LightGBM/python-package/lightgbm/basic.py
> Line 491 in ebb07f0

Traceback (most recent call last):
  File "gbm_train.py", line 71, in lgb_train
    train_leaves = gbm.predict(x_train, num_iteration=gbm.best_iteration, pred_leaf=Tru
e)
  File "/home/shuai.su/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 1784
, in predict
    return predictor.predict(data, num_iteration, raw_score, pred_leaf, pred_contrib, d
ata_has_header, is_reshape)
  File "/home/shuai.su/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 437,
 in predict
    predict_type)
  File "/home/shuai.su/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 491, in __pred_for_np2d
    preds = np.zeros(n_preds, dtype=np.float64)
ValueError: negative dimensions are not allowed

**Comment by supersush** [comment]
according to the traceback, i think it is caused by this line
https://github.com/Microsoft/LightGBM/blob/ebb07f019a611ec9d3712aadbc9e725faaa9c78c/python-package/lightgbm/basic.py#L491

Traceback (most recent call last):
File "gbm_train.py", line 71, in lgb_train
train_leaves = gbm.predict(x_train, num_iteration=gbm.best_iteration, pred_leaf=Tru
e)
File "/home/shuai.su/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 1784
, in predict
return predictor.predict(data, num_iteration, raw_score, pred_leaf, pred_contrib, d
ata_has_header, is_reshape)
File "/home/shuai.su/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 437,
in predict
predict_type)
File "/home/shuai.su/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 491, in __pred_for_np2d
preds = np.zeros(n_preds, dtype=np.float64)
ValueError: negative dimensions are not allowed

**Comment by supersush** [comment]
according to the traceback, i think it is caused by this line
https://github.com/Microsoft/LightGBM/blob/ebb07f019a611ec9d3712aadbc9e725faaa9c78c/python-package/lightgbm/basic.py#L491
@guolinke 
Traceback (most recent call last):
  File "gbm_train.py", line 71, in lgb_train
    train_leaves = gbm.predict(x_train, num_iteration=gbm.best_iteration, pred_leaf=True)
  File "/home/xx/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 1784, in predict
    return predictor.predict(data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape)
  File "/home/xx/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 437,in predict
    predict_type)
  File "/home/shuai.su/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 491, in __pred_for_np2d
    preds = np.zeros(n_preds, dtype=np.float64)
ValueError: negative dimensions are not allowed

**Comment by supersush** [comment]
according to the traceback, i think it is caused by this line
https://github.com/Microsoft/LightGBM/blob/ebb07f019a611ec9d3712aadbc9e725faaa9c78c/python-package/lightgbm/basic.py#L491
@guolinke 
Traceback (most recent call last):
  File "gbm_train.py", line 71, in lgb_train
    train_leaves = gbm.predict(x_train, num_iteration=gbm.best_iteration, pred_leaf=True)
  File "/home/xx/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 1784, in predict
    return predictor.predict(data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape)
  File "/home/xx/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 437,in predict
    predict_type)
  File "/home/xx/.local/lib/python2.7/site-packages/lightgbm/basic.py", line 491, in __pred_for_np2d
    preds = np.zeros(n_preds, dtype=np.float64)
ValueError: negative dimensions are not allowed

**Comment by supersush** [comment]
What make me more confused is that if i set 'num_trees': 20 ,  
gbm.predict(x_train, num_iteration=gbm.best_iteration, pred_leaf=True) will not throw any exception.
If set num_trees more than 20, this statement will throw the exception above. If i set pred_leaf=False，also will not throw throw exception.

**Comment by guolinke** [comment]
@supersush 
can you provide a reproduce code by random generated data?

**Comment by guolinke** [comment]
@supersush Okay, I see. I think the `n_preds` exceed the range of `int64_t` .
