### ISSUE TITLE
Continue Training issue (Using init_model param)

### ISSUE THREAD

**Issue by DeepakLabh** [Microsoft/LightGBM#1352]
reference code
```

    bst1 = lgb.train(lgb_params, 
                     xgtrain, 
                     # init_model = None,
                     # keep_training_booster = True,
                     valid_sets=[xgtrain, xgvalid], 
                     valid_names=['train','valid'], 
                     evals_result=evals_results, 
                     num_boost_round=num_boost_round,
                     early_stopping_rounds=early_stopping_rounds,
                     verbose_eval=10, 
                     feval=feval)

    bst1.save_model('models/lgb_best_model.txt',  num_iteration=bst1.best_iteration)
    print ('=======================================')
    bst1 = lgb.train(lgb_params, 
                     xgtrain, 
                     init_model = 'models/lgb_best_model.txt',
                     # keep_training_booster = True,
                     valid_sets=[xgtrain, xgvalid], 
                     valid_names=['train','valid'], 
                     evals_result=evals_results, 
                     num_boost_round=num_boost_round,
                     early_stopping_rounds=early_stopping_rounds,
                     verbose_eval=10, 
                     feval=feval)
```
Using init_model returns following error:

```
/home/deepak/venvs/py3env/lib/python3.5/site-packages/lightgbm/basic.py:1030: UserWarning: Using categorical_feature in Dataset.
  warnings.warn('Using categorical_feature in Dataset.')
/home/deepak/venvs/py3env/lib/python3.5/site-packages/lightgbm/basic.py:642: UserWarning: max_bin keyword has been found in `params` and will be ignored. Please use max_bin argument of the Dataset constructor to pass this parameter.
  'Please use {0} argument of the Dataset constructor to pass this parameter.'.format(key))
/home/deepak/venvs/py3env/lib/python3.5/site-packages/lightgbm/basic.py:671: UserWarning: categorical_feature in param dict is overrided.
  warnings.warn('categorical_feature in param dict is overrided.')
Training until validation scores don't improve for 30 rounds.
[10]    train's auc: 0.990863   valid's auc: 0.992731
[20]    train's auc: 0.993132   valid's auc: 0.991759
[30]    train's auc: 0.99321    valid's auc: 0.992141
Early stopping, best iteration is:
[9]     train's auc: 0.990911   valid's auc: 0.993587
=======================================
[LightGBM] [Fatal] Check failed: train_data->metadata().init_score() == nullptr at /home/travis/build/Microsoft/LightGBM/python-package/compile/src/boosting/rf.hpp, line 38 .

Traceback (most recent call last):
  File "models.py", line 454, in <module>
    (clf,best_iteration) = lgb_modelfit(params, train_df, val_df, predictors, target, objective='binary', metrics='auc',early_stopping_rounds=30, verbose_eval=True, num_boost_round=1000, categorical_features=categorical)
  File "models.py", line 146, in lgb_modelfit
    feval=feval)
  File "/home/deepak/venvs/py3env/lib/python3.5/site-packages/lightgbm/engine.py", line 178, in train
    booster = Booster(params=params, train_set=train_set)
  File "/home/deepak/venvs/py3env/lib/python3.5/site-packages/lightgbm/basic.py", line 1296, in __init__
    ctypes.byref(self.handle)))
  File "/home/deepak/venvs/py3env/lib/python3.5/site-packages/lightgbm/basic.py", line 48, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError())
lightgbm.basic.LightGBMError: b'Check failed: train_data->metadata().init_score() == nullptr at /home/travis/build/Microsoft/LightGBM/python-package/compile/src/boosting/rf.hpp, line 38 .\n'

```

**Comment by guolinke** [comment]
Sorry, RF(random forest) don't support continued training.

**Comment by DeepakLabh** [comment]
Thanks - Changed it to 'gbdt' and it worked..
