### ISSUE TITLE
ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by bedapisl** [Microsoft/LightGBM#1590]
## Environment info

Operating System: Debian 

CPU: x86_64

C++/Python/R version: python 3.4

## Error message

  File "/home/beda/venv/system3/lib/python3.4/site-packages/shap/explainers/tree.py", line 144, in shap_values
    phi = self.model.predict(X, num_iteration=tree_limit, pred_contrib=True)
  File "/home/beda/venv/system3/lib/python3.4/site-packages/lightgbm/basic.py", line 1802, in predict
    return predictor.predict(data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape)
  File "/home/beda/venv/system3/lib/python3.4/site-packages/lightgbm/basic.py", line 434, in predict
    predict_type)
  File "/home/beda/venv/system3/lib/python3.4/site-packages/lightgbm/basic.py", line 518, in __pred_for_csr
    preds = np.zeros(n_preds, dtype=np.float64)
ValueError: negative dimensions are not allowed

## Steps to reproduce

1. Call LGBMClassifier.predict with pred_contrib=True
2. As data pass CSR matrix with shape  (50000, 48793) or bigger

Probably 32-bit integer overflow when computing number of predictions.

**Comment by StrikerRUS** [comment]
Is it `pred_contrib`-specific problem?

Seems that `n_preds` doesn't suffer from int32 overflow:
https://github.com/Microsoft/LightGBM/blob/3400e3899d1c45997337bdbd0c8a2f729e805cbc/python-package/lightgbm/basic.py#L470

ping @guolinke

**Comment by StrikerRUS** [comment]
Thank you very much for the reproducible example, @bedapisl !

Indeed, increasing the limit of number of predictions yields another error:
```diff
diff --git a/python-package/lightgbm/basic.py b/python-package/lightgbm/basic.py
index 1072154..a10bad3 100644
--- a/python-package/lightgbm/basic.py
+++ b/python-package/lightgbm/basic.py
@@ -467,7 +467,7 @@ class _InnerPredictor(object):
         """
         Get size of prediction result
         """
-        n_preds = ctypes.c_int64(0)
+        n_preds = ctypes.c_uint64(0)
         _safe_call(_LIB.LGBM_BoosterCalcNumPredict(
             self.handle,
             ctypes.c_int(nrow),
```
```
...

C:\Miniconda3\lib\site-packages\lightgbm\basic.py in __pred_for_np2d(self, mat, num_iteration, predict_type)
    492         n_preds = self.__get_num_preds(num_iteration, mat.shape[0],
    493                                        predict_type)
--> 494         preds = np.zeros(n_preds, dtype=np.float64)
    495         out_num_preds = ctypes.c_int64(0)
    496         _safe_call(_LIB.LGBM_BoosterPredictForMat(

ValueError: Maximum allowed dimension exceeded
```

**Comment by StrikerRUS** [comment]
@guolinke 
numpy array length is limited only by the machine capability it running on (https://stackoverflow.com/a/23839975).

I printed `n_preds` before creating numpy array in [reproducible example](https://github.com/Microsoft/LightGBM/issues/1590#issuecomment-414654392) and it's `18 446 744 073 709 551 616` `(= 2^64)`. I suppose it's something at cpp side.

**Comment by guolinke** [comment]
@StrikerRUS @bedapisl 
can you try #1601?

log of my laptop with 16GB memory:
```
>>> classifier.fit(train_features, train_targets)
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
        importance_type='split', learning_rate=0.1, max_depth=-1,
        min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
        n_estimators=5, n_jobs=-1, num_leaves=31, objective=None,
        random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
        subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
>>>
>>> test_features_small = np.random.rand(2000000000, 2)
>>> classifier.predict(test_features_small)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\src\LightGBM\python-package\lightgbm\sklearn.py", line 715, in predict
    pred_leaf, pred_contrib, **kwargs)
  File "D:\src\LightGBM\python-package\lightgbm\sklearn.py", line 752, in predict_proba
    pred_leaf, pred_contrib, **kwargs)
  File "D:\src\LightGBM\python-package\lightgbm\sklearn.py", line 535, in predict
    pred_leaf=pred_leaf, pred_contrib=pred_contrib, **kwargs)
  File "D:\src\LightGBM\python-package\lightgbm\basic.py", line 1863, in predict
    return predictor.predict(data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape)
  File "D:\src\LightGBM\python-package\lightgbm\basic.py", line 440, in predict
    predict_type)
  File "D:\src\LightGBM\python-package\lightgbm\basic.py", line 494, in __pred_for_np2d
    preds = np.zeros(n_preds, dtype=np.float64)
MemoryError
```

**Comment by StrikerRUS** [comment]
112 GB RAM `fix-array-size` branch with printing `n_preds` yields the same error:
```
>>> classifier.predict(test_features_big)


-1294967296
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-841a61992bcd> in <module>()
----> 1 classifier.predict(test_features_big)

C:\Miniconda3\lib\site-packages\lightgbm\sklearn.py in predict(self, X, raw_score, num_iteration, pred_leaf, pred_contrib, **kwargs)
    713                 pred_leaf=False, pred_contrib=False, **kwargs):
    714         result = self.predict_proba(X, raw_score, num_iteration,
--> 715                                     pred_leaf, pred_contrib, **kwargs)
    716         if raw_score or pred_leaf or pred_contrib:
    717             return result

C:\Miniconda3\lib\site-packages\lightgbm\sklearn.py in predict_proba(self, X, raw_score, num_iteration, pred_leaf, pred_contrib, **kwargs)
    750         """
    751         result = super(LGBMClassifier, self).predict(X, raw_score, num_iteration,
--> 752                                                      pred_leaf, pred_contrib, **kwargs)
    753         if self._n_classes > 2 or pred_leaf or pred_contrib:
    754             return result

C:\Miniconda3\lib\site-packages\lightgbm\sklearn.py in predict(self, X, raw_score, num_iteration, pred_leaf, pred_contrib, **kwargs)
    533                              % (self._n_features, n_features))
    534         return self.booster_.predict(X, raw_score=raw_score, num_iteration=num_iteration,
--> 535                                      pred_leaf=pred_leaf, pred_contrib=pred_contrib, **kwargs)
    536 
    537     def apply(self, X, num_iteration=0):

C:\Miniconda3\lib\site-packages\lightgbm\basic.py in predict(self, data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape, pred_parameter, **kwargs)
   1862         if num_iteration is None:
   1863             num_iteration = self.best_iteration
-> 1864         return predictor.predict(data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape)
   1865 
   1866     def get_leaf_output(self, tree_id, leaf_id):

C:\Miniconda3\lib\site-packages\lightgbm\basic.py in predict(self, data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape)
    438         elif isinstance(data, np.ndarray):
    439             preds, nrow = self.__pred_for_np2d(data, num_iteration,
--> 440                                                predict_type)
    441         elif isinstance(data, list):
    442             try:

C:\Miniconda3\lib\site-packages\lightgbm\basic.py in __pred_for_np2d(self, mat, num_iteration, predict_type)
    493                                        predict_type)
    494         print(n_preds)
--> 495         preds = np.zeros(n_preds, dtype=np.float64)
    496         out_num_preds = ctypes.c_int64(0)
    497         _safe_call(_LIB.LGBM_BoosterPredictForMat(

ValueError: negative dimensions are not allowed
```

And after changing to `uint` https://github.com/Microsoft/LightGBM/issues/1590#issuecomment-414695622:

```
>>> classifier.predict(test_features_big)


18446744072414584320
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-841a61992bcd> in <module>()
----> 1 classifier.predict(test_features_big)

C:\Miniconda3\lib\site-packages\lightgbm\sklearn.py in predict(self, X, raw_score, num_iteration, pred_leaf, pred_contrib, **kwargs)
    713                 pred_leaf=False, pred_contrib=False, **kwargs):
    714         result = self.predict_proba(X, raw_score, num_iteration,
--> 715                                     pred_leaf, pred_contrib, **kwargs)
    716         if raw_score or pred_leaf or pred_contrib:
    717             return result

C:\Miniconda3\lib\site-packages\lightgbm\sklearn.py in predict_proba(self, X, raw_score, num_iteration, pred_leaf, pred_contrib, **kwargs)
    750         """
    751         result = super(LGBMClassifier, self).predict(X, raw_score, num_iteration,
--> 752                                                      pred_leaf, pred_contrib, **kwargs)
    753         if self._n_classes > 2 or pred_leaf or pred_contrib:
    754             return result

C:\Miniconda3\lib\site-packages\lightgbm\sklearn.py in predict(self, X, raw_score, num_iteration, pred_leaf, pred_contrib, **kwargs)
    533                              % (self._n_features, n_features))
    534         return self.booster_.predict(X, raw_score=raw_score, num_iteration=num_iteration,
--> 535                                      pred_leaf=pred_leaf, pred_contrib=pred_contrib, **kwargs)
    536 
    537     def apply(self, X, num_iteration=0):

C:\Miniconda3\lib\site-packages\lightgbm\basic.py in predict(self, data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape, pred_parameter, **kwargs)
   1862         if num_iteration is None:
   1863             num_iteration = self.best_iteration
-> 1864         return predictor.predict(data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape)
   1865 
   1866     def get_leaf_output(self, tree_id, leaf_id):

C:\Miniconda3\lib\site-packages\lightgbm\basic.py in predict(self, data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape)
    438         elif isinstance(data, np.ndarray):
    439             preds, nrow = self.__pred_for_np2d(data, num_iteration,
--> 440                                                predict_type)
    441         elif isinstance(data, list):
    442             try:

C:\Miniconda3\lib\site-packages\lightgbm\basic.py in __pred_for_np2d(self, mat, num_iteration, predict_type)
    493                                        predict_type)
    494         print(n_preds)
--> 495         preds = np.zeros(n_preds, dtype=np.float64)
    496         out_num_preds = ctypes.c_int64(0)
    497         _safe_call(_LIB.LGBM_BoosterPredictForMat(

ValueError: Maximum allowed dimension exceeded
```

**Comment by guolinke** [comment]
I think the reason is the `nrow` exceed the 32-bit range. The c_api only accept the int32 for now.

**Comment by guolinke** [comment]
due to the efficiency concern, LightGBM only accept the int32 nrow. 
For the nrow exceed the 32-bit ranges, please consider split it to multi data for prediction, and then concat back. 
@StrikerRUS Do you think we can have this split-concat logics inside LightGBM python package ?

**Comment by guolinke** [comment]
@bedapisl I think your origin pred-contrib problem should be fixed by #1601 . Can you try it again.

**Comment by StrikerRUS** [comment]
>Do you think we can have this split-concat logics inside LightGBM python package ?

Despite the fact that this is not the common use case, it sounds reasonable!

**Comment by bedapisl** [comment]
@guolinke I tried your fix, but it didn't help. Although I am not 100% sure I was trying the correct version. To try your fix I runned in LightGBM directory:
```
git checkout master
git pull
mkdir build
cd  build
cmake ..
make -j 20
cd ../python-package
python setup.py develop
```
And then runned my script.

**Comment by guolinke** [comment]
@bedapisl can you provide a reproduce example of pred-contrib ?

**Comment by bedapisl** [comment]
```
from lightgbm import LGBMClassifier
import numpy as np

classifier = LGBMClassifier(n_estimators=5)

train_features = np.random.rand(100, 1000)
train_targets = [0] * 50 + [1] * 50

classifier.fit(train_features, train_targets)

test_features = np.random.rand(3000000, 1000)

classifier.predict(test_features, pred_contrib=True)
```
This gives the error:
```
Traceback (most recent call last):
  File "minimal_error_pred_contrib.py", line 13, in <module>
    classifier.predict(test_features, pred_contrib=True)
  File "/home/beda/venv/system3/lib/python3.4/site-packages/lightgbm/sklearn.py", line 706, in predict
    pred_leaf, pred_contrib, **kwargs)
  File "/home/beda/venv/system3/lib/python3.4/site-packages/lightgbm/sklearn.py", line 742, in predict_proba
    pred_leaf, pred_contrib, **kwargs)
  File "/home/beda/venv/system3/lib/python3.4/site-packages/lightgbm/sklearn.py", line 528, in predict
    pred_leaf=pred_leaf, pred_contrib=pred_contrib, **kwargs)
  File "/home/beda/venv/system3/lib/python3.4/site-packages/lightgbm/basic.py", line 1802, in predict
    return predictor.predict(data, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape)
  File "/home/beda/venv/system3/lib/python3.4/site-packages/lightgbm/basic.py", line 440, in predict
    predict_type)
  File "/home/beda/venv/system3/lib/python3.4/site-packages/lightgbm/basic.py", line 494, in __pred_for_np2d
    preds = np.zeros(n_preds, dtype=np.float64)
ValueError: negative dimensions are not allowed
```

**Comment by guolinke** [comment]
@bedapisl 
just try it, and seems I didn't get this error.
And I also print the `n_preds` before line 494, and the result is `3003000000`.
Can you try to delete and re-clone, then re-install again ? 

@StrikerRUS can you help to check it as well ?

**Comment by StrikerRUS** [comment]
I confirm this https://github.com/Microsoft/LightGBM/issues/1590#issuecomment-415412993 .
`n_preds = 3003000000` and prediction works fine.

**Comment by bedapisl** [comment]
I can also confirm that script with pred_contrib=True ([https://github.com/Microsoft/LightGBM/issues/1590#issuecomment-415359078](https://github.com/Microsoft/LightGBM/issues/1590#issuecomment-415359078)) works without any errors.

**Comment by StrikerRUS** [comment]
@bedapisl Can you please check `pred-chunks` branch?

For me, your example in https://github.com/Microsoft/LightGBM/issues/1590#issuecomment-414654392 works fine.

**Comment by bedapisl** [comment]
@StrikerRUS It works for me too.

**Comment by StrikerRUS** [comment]
@bedapisl Thank you for your response!
I'm reopening this issue, because the fix isn't in the `master` branch yet.

In addition, can I ask you to check scipy.sparse input too? But it'll be a little bit later.

**Comment by bedapisl** [comment]
The example without `pred_contrib` works also with csr_matrix. And please don't ask me to check other things, it's quite time-consuming for me.
Anyway, thanks for the fixes.

**Comment by StrikerRUS** [comment]
@bedapisl 
Got it! Thank you very much for feedback!
