### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by pseudotensor** [Microsoft/LightGBM#1971]
[fail.zip](https://github.com/Microsoft/LightGBM/files/2799905/fail.zip)

Code was compiled for GPU.  Uses hash: d169ac8b7049d3e8345e70288f19eaa7dfb8fe38

Issue has been there for many months, but we noticed it happening for non-trivial data as well so now posting issue with example.

**Comment by guolinke** [comment]
The root cause is the `nan` in evaluation score, and cause the wrong comparison result in early stopping.

**Comment by pseudotensor** [comment]
So you don't have concerns about the data itself or the parameters?  And the above fix should be good for these cases we see (many, especially for objectives other than plain regression) this score error -> NoneType issue?

**Comment by guolinke** [comment]
In gamma regression, the label should greater zero;
https://github.com/Microsoft/LightGBM/blob/52dbc5722fe0b80d224ee33ba5b064b80966e6c6/src/metric/regression_metric.hpp#L255
But in your code, there are many labels with zeros. 
I think we should throw the error in these cases.

**Comment by pseudotensor** [comment]
yes a direct error would be good

**Comment by pseudotensor** [comment]
I think main issue here is that lightgbm thinks no trees are better than any amount of trees, and then the score becomes bad.

This is related to an issue before, when lightgbm would fail to generate at least an average (for regression) or most-common (for classification) target as the base model.

**Comment by pseudotensor** [comment]
I'll try to find another case that isn't with a less common objective.

**Comment by pseudotensor** [comment]
[fail5.zip](https://github.com/Microsoft/LightGBM/files/2801843/fail5.zip)

Here's another case that fails in the same way.  Yes, features are funny, but target is normal.  Shouldn't fail.  Should at least be able to recover average (for regression) or most frequent (for classification) model.

**Comment by guolinke** [comment]
@pseudotensor Actually, LightGBM have dummy trees for these cases.
I edit your pasted code for test that.

```
import _pickle as pickle
import pandas as pd
import numpy as np
import lightgbm as lgb
model = lgb.LGBMRegressor(bagging_seed=3137599, boosting_type='gbdt', class_weight=None,
                             colsample_bytree=0.8, 
                             feature_fraction_seed=3137598, gpu_device_id=1, gpu_platform_id=0,
                             importance_type='gain', learning_rate=0.05, max_bin=255,
                             max_delta_step=0, max_depth=-1, min_child_samples=1,
                             min_child_weight=1, min_data_in_bin=1, min_split_gain=0.0,
                             n_estimators=600, n_jobs=4, num_class=1, num_leaves=64,
                             objective='regression', random_state=None, reg_alpha=0.0,
                             reg_lambda=1.0, scale_pos_weight=1, silent=True, subsample=1.0,
                             subsample_for_bin=200000, subsample_freq=1, verbose=2)
X, y, sample_weight, init_score, eval_set, valid_X_features, eval_sample_weight, init_score, eval_metric, early_stopping_rounds, X_features, verbose_fit = pickle.load(open("data.pkl", "rb"))
y = y/y.max()
valid_y = eval_set[0][1]
# below uncommented has no issues
#valid_y = valid_y/valid_y.max()
eval_set[0] = (eval_set[0][0], valid_y)
model.fit(X, y)
p = model.predict(eval_set[0][0])
```

and the values of p is
```
array([0.33332364, 0.33332364, 0.33332364, ..., 0.33332364, 0.33332364,
       0.33332364])
```

The fail result is the same as above case, due to the l2 loss is inf (too large range of test label).

**Comment by pseudotensor** [comment]
Something is off, perhaps GPU vs. CPU trainer?  Here's my output:
```
$ python fail.py
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 5
[LightGBM] [Info] Number of data: 111671, number of used features: 1
[LightGBM] [Info] Using requested OpenCL platform 0 device 1
[LightGBM] [Info] Using GPU Device: GeForce GTX 1080 Ti, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 16 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 12
[LightGBM] [Info] 1 dense feature groups (0.43 MB) transfered to GPU in 0.001917 secs. 0 sparse feature groups
[LightGBM] [Info] Start training from score 0.333334
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[1]     valid_0's rmse: inf     valid_0's l2: inf
Training until validation scores don't improve for 20 rounds.
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[2]     valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[3]     valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[4]     valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[5]     valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[6]     valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[7]     valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[8]     valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[9]     valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[10]    valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[11]    valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[12]    valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[13]    valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[14]    valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[15]    valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[16]    valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[17]    valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[18]    valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[19]    valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[20]    valid_0's rmse: inf     valid_0's l2: inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Debug] Trained a tree with leaves = 3 and max_depth = 2
[21]    valid_0's rmse: inf     valid_0's l2: inf
Traceback (most recent call last):
  File "fail.py", line 21, in <module>
    model.fit(X, y, eval_set=eval_set, eval_sample_weight=eval_sample_weight, eval_metric=eval_metric, early_stopping_rounds=early_stopping_rounds)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/lightgbm_gpu/sklearn.py", line 642, in fit
    callbacks=callbacks)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/lightgbm_gpu/sklearn.py", line 502, in fit
    callbacks=callbacks)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/lightgbm_gpu/engine.py", line 228, in train
    evaluation_result_list=evaluation_result_list))
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/lightgbm_gpu/callback.py", line 214, in callback
    best_iter[i] + 1, '\t'.join([_format_eval_result(x) for x in best_score_list[i]])))
TypeError: 'NoneType' object is not iterable
```

**Comment by pseudotensor** [comment]
I'll check to make sure I have correct version.

**Comment by pseudotensor** [comment]
Ah yes, sorry, for this test I went back and hunted for the older time when I got this failure, and I conflated this with the new gamma objective related failure.

**Comment by pseudotensor** [comment]
Ok, I think as long as the error is improved, this can be closed.

**Comment by pseudotensor** [comment]
Here is a corner case that could be fixed too:

[fail6.zip](https://github.com/Microsoft/LightGBM/files/2804918/fail6.zip)

Basically all sample weights for the eval set are 0.  But even if the eval set can't be used for some reason, should at least be able to predict the average (dummy trees) model.

**Comment by guolinke** [comment]
@pseudotensor 
It actually has the dummy trees. tested by your code
```
model.fit(X, y, sample_weight=sample_weight, init_score=init_score, eval_set=eval_set, eval_init_score=init_score, eval_metric=eval_metric, eval_sample_weight=eval_sample_weight)
model.predict(X)
model.predict(eval_set[0][0])
```
As well as the early_stopping_rounds is removed, the model can provide the average prediction.

**Comment by pseudotensor** [comment]
Understood, but even if there is a bad eval_set or early stopping, the worse case should be dummy trees always.  It shouldn't have failed even with early stopping turned on.

**Comment by guolinke** [comment]
@pseudotensor yeah, the fixes are in https://github.com/Microsoft/LightGBM/pull/1973
and your cases are added as test cases 😄

**Comment by pseudotensor** [comment]
Awesome, thanks!
