### ISSUE TITLE
SIGSEGV in LightGBM::RegressionMAPELOSS::RenewTreeOutput

### ISSUE THREAD

**Issue by pseudotensor** [Microsoft/LightGBM#1972]
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `_h2oai-test_random_6385569-auto_dl:Model_and_feature_tun'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f7c6624416b in LightGBM::RegressionMAPELOSS::RenewTreeOutput(double, double const*, int const*, int const*, int) const () from /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/lightgbm_gpu/lib_lightgbm.so
[Current thread is 1 (Thread 0x7f7c20e49700 (LWP 3169))]
(gdb) bt
#0  0x00007f7c6624416b in LightGBM::RegressionMAPELOSS::RenewTreeOutput(double, double const*, int const*, int const*, int) const () from /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/lightgbm_gpu/lib_lightgbm.so
#1  0x00007f7c6627c3ad in LightGBM::SerialTreeLearner::RenewTreeOutput(LightGBM::Tree*, LightGBM::ObjectiveFunction const*, double const*, int, int const*, int) const [clone ._omp_fn.26] () from /home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/lightgbm_gpu/lib_lightgbm.so
#2  0x00007f7b7c30f43e in ?? () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#3  0x00007f7c8aaf66ba in start_thread (arg=0x7f7c20e49700) at pthread_create.c:333
#4  0x00007f7c8a82c41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```

```
[LightGBM] [Fatal] Check failed: threshold < weighted_cdf[pos] at /root/repo/LightGBM/src/objective/regression_objective.hpp, line 691 .

terminate called after throwing an instance of 'std::runtime_error'
  what():  Check failed: threshold < weighted_cdf[pos] at /root/repo/LightGBM/src/objective/regression_objective.hpp, line 691 .
```

[fail2.zip](https://github.com/Microsoft/LightGBM/files/2799933/fail2.zip)

**Comment by pseudotensor** [comment]
[fail4.zip](https://github.com/Microsoft/LightGBM/files/2799956/fail4.zip)

**Comment by guolinke** [comment]
I try your code in the master branch and don't throw this error...
I think I fix this in this commit: https://github.com/Microsoft/LightGBM/commit/0f224c05683991d84ab38cb1730195a1c57ff487#diff-9af477d6143aa9014f951ff8f1848c4b

**Comment by pseudotensor** [comment]
Hi, I'm using hash: d169ac8b7049d3e8345e70288f19eaa7dfb8fe38 from Jan 20, so that commit couldn't fix it.

I provided 4 different fail scripts+data, and all of them worked for you?

**Comment by pseudotensor** [comment]
Ya, I can send fail3.zip data separately, kinda big.  Sorry about fail4, will send fixed zip.

**Comment by pseudotensor** [comment]
[fail4_fixed.zip](https://github.com/Microsoft/LightGBM/files/2801904/fail4_fixed.zip)

**Comment by guolinke** [comment]
@pseudotensor Thanks, you are right, there are some other edge cases. I just fix them.
