### ISSUE TITLE
inf/nan from finite input -> TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by pseudotensor** [Microsoft/LightGBM#1994]
[fail8.zip](https://github.com/Microsoft/LightGBM/files/2825447/fail8.zip)

```
$ python fail.py
True
True
True
True
True
[1]     valid_0's l1: inf
Training until validation scores don't improve for 20 rounds.
[2]     valid_0's l1: nan
[3]     valid_0's l1: nan
[4]     valid_0's l1: nan
[5]     valid_0's l1: nan
[6]     valid_0's l1: nan
[7]     valid_0's l1: nan
[8]     valid_0's l1: nan
[9]     valid_0's l1: nan
[10]    valid_0's l1: nan
[11]    valid_0's l1: nan
[12]    valid_0's l1: nan
[13]    valid_0's l1: nan
[14]    valid_0's l1: nan
[15]    valid_0's l1: nan
[16]    valid_0's l1: nan
[17]    valid_0's l1: nan
[18]    valid_0's l1: nan
[19]    valid_0's l1: nan
[20]    valid_0's l1: nan
[21]    valid_0's l1: nan
Traceback (most recent call last):
  File "fail.py", line 24, in <module>
    model.fit(X, y, sample_weight=sample_weight,eval_set=eval_set, eval_metric=eval_metric, early_stopping_rounds=early_stopping_rounds)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/lightgbm_gpu/sklearn.py", line 685, in fit
    callbacks=callbacks)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/lightgbm_gpu/sklearn.py", line 544, in fit
    callbacks=callbacks)
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/lightgbm_gpu/engine.py", line 233, in train
    evaluation_result_list=evaluation_result_list))
  File "/home/jon/.pyenv/versions/3.6.4/lib/python3.6/site-packages/lightgbm_gpu/callback.py", line 223, in _callback
    best_iter[i] + 1, '\t'.join([_format_eval_result(x) for x in best_score_list[i]])))
TypeError: 'NoneType' object is not iterable

```

**Comment by pseudotensor** [comment]
I have a2f5c50ca80dce9283b4170374d277799a4bad7b .  I'll try after your above fix.

**Comment by pseudotensor** [comment]
I tried your latest and it is fixed:

```
$ python fail.py
True
True
True
True
True
[1]     valid_0's l1: 182411
Training until validation scores don't improve for 20 rounds.
[2]     valid_0's l1: 165610
[3]     valid_0's l1: 164698
[4]     valid_0's l1: 149949
[5]     valid_0's l1: 149912
[6]     valid_0's l1: 138177
[7]     valid_0's l1: 137767
[8]     valid_0's l1: 127428
[9]     valid_0's l1: 127350
[10]    valid_0's l1: 118425
[11]    valid_0's l1: 118662
[12]    valid_0's l1: 110786
[13]    valid_0's l1: 111103
[14]    valid_0's l1: 103831
[15]    valid_0's l1: 104056
[16]    valid_0's l1: 98700.9
[17]    valid_0's l1: 98771.5
[18]    valid_0's l1: 94816.8
[19]    valid_0's l1: 94573.7
[20]    valid_0's l1: 91350.6
[21]    valid_0's l1: 91044.4
[22]    valid_0's l1: 87491.6
[23]    valid_0's l1: 87551.7
[24]    valid_0's l1: 84492.5
[25]    valid_0's l1: 84582.4
[26]    valid_0's l1: 81884.4
[27]    valid_0's l1: 81834.7
[28]    valid_0's l1: 79482.2
[29]    valid_0's l1: 79278.4
[30]    valid_0's l1: 77046.4
[31]    valid_0's l1: 76973.6
[32]    valid_0's l1: 75105.7
[33]    valid_0's l1: 74675.3
[34]    valid_0's l1: 72925.2
[35]    valid_0's l1: 72833.4
[36]    valid_0's l1: 71305.9
[37]    valid_0's l1: 71569.2
[38]    valid_0's l1: 69371
[39]    valid_0's l1: 69227.3
[40]    valid_0's l1: 67813.9
[41]    valid_0's l1: 67467.3
[42]    valid_0's l1: 66347.5
[43]    valid_0's l1: 66438.7
[44]    valid_0's l1: 65463.3
[45]    valid_0's l1: 65455.2
[46]    valid_0's l1: 64737.9
[47]    valid_0's l1: 64866.9
[48]    valid_0's l1: 64341.3
[49]    valid_0's l1: 64397
[50]    valid_0's l1: 63816.4
[51]    valid_0's l1: 63729.4
[52]    valid_0's l1: 63252.3
[53]    valid_0's l1: 63356.2
[54]    valid_0's l1: 62844.9
[55]    valid_0's l1: 63021.2
[56]    valid_0's l1: 62601.6
[57]    valid_0's l1: 62820.5
[58]    valid_0's l1: 62410.6
[59]    valid_0's l1: 62463.5
[60]    valid_0's l1: 62241
[61]    valid_0's l1: 62420.2
[62]    valid_0's l1: 62229.1
[63]    valid_0's l1: 62086.9
[64]    valid_0's l1: 61816.2
[65]    valid_0's l1: 61914.2
[66]    valid_0's l1: 61641.6
[67]    valid_0's l1: 61641.6
[68]    valid_0's l1: 61519.9
[69]    valid_0's l1: 61612.9
[70]    valid_0's l1: 61397.9
[71]    valid_0's l1: 61650.5
[72]    valid_0's l1: 61633.9
[73]    valid_0's l1: 61783
[74]    valid_0's l1: 61570.5
[75]    valid_0's l1: 61524.6
[76]    valid_0's l1: 61417.1
[77]    valid_0's l1: 61553.3
[78]    valid_0's l1: 61471.3
[79]    valid_0's l1: 61579.5
[80]    valid_0's l1: 61493.5
[81]    valid_0's l1: 61580.3
[82]    valid_0's l1: 61403.5
[83]    valid_0's l1: 61451.2
[84]    valid_0's l1: 61507.2
[85]    valid_0's l1: 61682.9
[86]    valid_0's l1: 62019.2
[87]    valid_0's l1: 62086.2
[88]    valid_0's l1: 61968.3
[89]    valid_0's l1: 61891.3
[90]    valid_0's l1: 61784.1
Early stopping, best iteration is:
[70]    valid_0's l1: 61397.9
```
