### ISSUE TITLE
version `GLIBCXX_3.4.20' not found error on version 0.16

### ISSUE THREAD

**Issue by land1725** [Microsoft/LightGBM#2087]
## Steps to reproduce

@imatiach-msft 

Hello,I am so sorry to tell that when I use latest version 0.16 lightgbm on Centos 7, it reported a problem like follow.

Could you help me to rebuild the PR on Centos 7 for me ,and provided the maven address to download ,thanks a lot

## Environment info

Operating System:Centos 7

CPU/GPU model:

C++/Python/R version:

LightGBM version or commit hash:
<dependency>
    <groupId>com.microsoft.ml.spark</groupId>
    <artifactId>mmlspark</artifactId>
    <version>0.16</version>
</dependency>
## Error message

19/04/09 16:42:36 WARN scheduler.TaskSetManager: Lost task 1.3 in stage 55.0 (TID 2630, bigdata.node4, executor 11): java.lang.UnsatisfiedLinkError: /data/cdh/yarn/nm/usercache/hadoop/appcache/application_1551665533369_6101/container_1551665533369_6101_01_000012/tmp/mml-natives1856917939260632129/lib_lightgbm.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /data/cdh/yarn/nm/usercache/hadoop/appcache/application_1551665533369_6101/container_1551665533369_6101_01_000012/tmp/mml-natives1856917939260632129/lib_lightgbm.so)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1086)
	at com.microsoft.ml.spark.NativeLoader.loadLibraryByName(NativeLoader.java:59)
	at com.microsoft.ml.spark.LightGBMUtils$.initializeNativeLibrary(LightGBMUtils.scala:38)
	at com.microsoft.ml.spark.TrainUtils$$anonfun$5.apply(TrainUtils.scala:208)
	at com.microsoft.ml.spark.TrainUtils$$anonfun$5.apply(TrainUtils.scala:205)
	at com.microsoft.ml.spark.StreamUtilities$.using(StreamUtilities.scala:29)
	at com.microsoft.ml.spark.TrainUtils$.trainLightGBM(TrainUtils.scala:204)
	at com.microsoft.ml.spark.LightGBMClassifier$$anonfun$3.apply(LightGBMClassifier.scala:83)
	at com.microsoft.ml.spark.LightGBMClassifier$$anonfun$3.apply(LightGBMClassifier.scala:83)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:188)
	at org.apache.spark.sql.execution.MapPartitionsExec$$anonfun$5.apply(objects.scala:185)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:830)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:830)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by StrikerRUS** [comment]
@land1725 Sorry that you have this problem on your CentOS!
I thinks that you'll get response faster if you re-post this in https://github.com/Azure/mmlspark repository. We do not maintain MMLSpark here. Furthermore, you've already reported your case in https://github.com/Microsoft/LightGBM/issues/1945#issuecomment-480772754. There are no need to create a separate issue for this. So, I'm going to close this as duplicated one.

Please continue the discussion in #1945.
