### ISSUE TITLE
UnsatisfiedLinkError when call method through swig and JNI

### ISSUE THREAD

**Issue by dusj** [microsoft/LightGBM#2250]
## Environment info

Operating System:  Red Hat 4.8.5-11

CPU/GPU model:  32  Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz

C++/Python/R version:  gcc version 4.8.5

LightGBM version or commit hash: 16751b3

## Error message

Invocation of init method failed; nested exception is java.lang.Unsatisfied
LinkError: com.microsoft.lightgbm.lightgbmlibJNI.new_intp()J
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1568)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:540)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:229)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:762)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
        at net.paoding.rose.RoseFilter.prepareRootApplicationContext(RoseFilter.java:425)
        at net.paoding.rose.RoseFilter.initFilterBean(RoseFilter.java:268)
        at org.springframework.web.filter.GenericFilterBean.init(GenericFilterBean.java:199)
        at com.caucho.server.dispatch.FilterManager.createFilter(FilterManager.java:204)
        at com.caucho.server.dispatch.FilterManager.init(FilterManager.java:105)
        at com.caucho.server.webapp.WebApp.startImpl(WebApp.java:3696)
        at com.caucho.server.webapp.WebApp.access$400(WebApp.java:207)
        at com.caucho.server.webapp.WebApp$StartupTask.run(WebApp.java:5234)
        at com.caucho.env.thread2.ResinThread2.runTasks(ResinThread2.java:173)
        at com.caucho.env.thread2.ResinThread2.run(ResinThread2.java:118)
Caused by: java.lang.UnsatisfiedLinkError: com.microsoft.lightgbm.lightgbmlibJNI.new_intp()J
        at com.microsoft.lightgbm.lightgbmlibJNI.new_intp(Native Method)
        at com.microsoft.lightgbm.lightgbmlib.new_intp(lightgbmlib.java:290)

## Steps to reproduce

1. compile code，build so file
2. compile swig api inference, package to a jar.
3. in java code, call any method by swig，such as: 
SWIGTYPE_p_int numIterations = lightgbmlib.new_intp();

**Comment by pmjpawelec** [comment]
I can confirm it works. Make sure you made the JNI work:

1. The `so` files have to be available in `java,library.path`. I took them out of the jar.

2. You have to load both `so`s using `System.loadLibrary("lightgbm")` and `System.loadLibrary("lightgbmJNI")`

anyway, it's not a LightGBM issue.

**Comment by StrikerRUS** [comment]
ping @imatiach-msft for confirmation

**Comment by StrikerRUS** [comment]
@imatiach-msft

**Comment by imatiach-msft** [comment]
@StrikerRUS @dusj  yes, confirmed, this should work - most likely the so files aren't found (Sorry for the late response, didn't see this earlier in my inbox)

**Comment by StrikerRUS** [comment]
@imatiach-msft Thanks for the response!
