### ISSUE TITLE
There comes an error when I set the weights

### ISSUE THREAD

**Issue by Kyla0606** [Microsoft/LightGBM#231]
I used the following example code in https://github.com/Microsoft/LightGBM/blob/master/docs/Python-intro.md:
`data = np.random.rand(500,10) `
`label = np.random.randint(2, size=500)`
`w = np.random.rand(500, 1)`
`train_data = lgb.Dataset(data, label=label, weight=w)`
`param = {'num_leaves':31, 'num_trees':100, 'objective':'binary' }`
`num_round = 10`
`bst = lgb.train(param, train_data, num_round)`
And there comes an error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/lightgbm-0.1-py2.7.egg/lightgbm/engine.py", line 163, in train
    booster = Booster(params=params, train_set=train_set)
  File "/usr/local/lib/python2.7/dist-packages/lightgbm-0.1-py2.7.egg/lightgbm/basic.py", line 1165, in __init__
    train_set.construct().handle,
  File "/usr/local/lib/python2.7/dist-packages/lightgbm-0.1-py2.7.egg/lightgbm/basic.py", line 763, in construct
    categorical_feature=self.categorical_feature, params=self.params)
  File "/usr/local/lib/python2.7/dist-packages/lightgbm-0.1-py2.7.egg/lightgbm/basic.py", line 640, in _lazy_init
    self.set_weight(weight)
  File "/usr/local/lib/python2.7/dist-packages/lightgbm-0.1-py2.7.egg/lightgbm/basic.py", line 1013, in set_weight
    weight = list_to_1d_numpy(weight, name='weight')
  File "/usr/local/lib/python2.7/dist-packages/lightgbm-0.1-py2.7.egg/lightgbm/basic.py", line 82, in list_to_1d_numpy
    raise TypeError("Wrong type({}) for {}, should be list or numpy array".format(type(data).__name__, name))
TypeError: Wrong type(ndarray) for weight, should be list or numpy array

**Comment by wxchan** [comment]
`w = np.random.rand(500, 1)` -> `w = np.random.rand(500, )`

**Comment by Kyla0606** [comment]
Gotcha, thanks.
