### ISSUE TITLE
custom objective in Random Forest mode

### ISSUE THREAD

**Issue by slonoslon** [microsoft/LightGBM#2328]
Is custom objective function supported when boosting_type is 'rf'? If not, at least a more informative error message would be helpful.

## Environment info

LightGBM version or commit hash:

2.2.4

## Error message

```
[LightGBM] [Fatal] No object function provided
Traceback (most recent call last):
  File "lgbm_custom_objective.py", line 10, in <module>
    gbm = lgb.train(params, lgb_train, num_boost_round=10, fobj=custom_objective)
  File "/opt/miniconda/lib/python3.6/site-packages/lightgbm/engine.py", line 227, in train
    booster = Booster(params=params, train_set=train_set)
  File "/opt/miniconda/lib/python3.6/site-packages/lightgbm/basic.py", line 1659, in __init__
    ctypes.byref(self.handle)))
  File "/opt/miniconda/lib/python3.6/site-packages/lightgbm/basic.py", line 47, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: No object function provided

```
## Reproducible examples

```
import numpy as np
import lightgbm as lgb

def custom_objective(y_true, y_test):
    return np.zeros_like(y_true), np.zeros_like(y_true)


params = {'boosting_type': 'rf', 'bagging_fraction': 0.6, 'bagging_freq': 1}
lgb_train = lgb.Dataset(np.random.random(size=(100, 100)), np.random.random(size=100))
gbm = lgb.train(params, lgb_train, num_boost_round=10, fobj=custom_objective)

```

**Comment by guolinke** [comment]
@slonoslon 
yes, the RF cannot support custom objective now. 
refer to https://github.com/microsoft/LightGBM/blob/46d2147684a86d7b4219c83386c469d34c1b075f/src/boosting/rf.hpp#L84
