### ISSUE TITLE
[python package] lgbm.Booster() can't read type:rank_xendcg

### ISSUE THREAD

**Issue by araman0** [microsoft/LightGBM#2739]
## Environment info

Operating System:

CPU/GPU model: CPU model

C++/Python/R version: Python3.6.5

LightGBM version or commit hash: dbb804f2350f280f3c927f792f7e55ac9c021707

## Error message

```sh
$ cat gain_imp.py 
import lightgbm as lgbm
import argparse


def main():
    parser = argparse.ArgumentParser(description='calc importance by gain')
    parser.add_argument('model', metavar='model_file', help='model file path')
    args = parser.parse_args()


    lgbm_model = lgbm.Booster(model_file=args.model)
    importance = lgbm_model.feature_importance(importance_type="gain")
    features = lgbm_model.feature_name()


if __name__ == '__main__':
    main()

$ python gain_imp.py LightGBM_model.txt 
[LightGBM] [Fatal] Unknown objective type name: rank_xendcg
Traceback (most recent call last):
  File "gain_imp.py", line 25, in <module>
    main()
  File "gain_imp.py", line 11, in main
    lgbm_model = lgbm.Booster(model_file=args.model)
  File "/opt/python36/lib/python3.6/site-packages/lightgbm/basic.py", line 1744, in __init__
    ctypes.byref(self.handle)))
  File "/opt/python36/lib/python3.6/site-packages/lightgbm/basic.py", line 45, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: Unknown objective type name: rank_xendcg
```

## Steps to reproduce
```
$ cd LightGBM/examples/xendcg/
$ ../../lightgbm config=train.conf 
$ python gain_imp.py LightGBM_model.txt 
```

**Comment by araman0** [comment]
```
$ pip list | grep lightgbm
lightgbm                             2.3.1 
```

**Comment by guolinke** [comment]
xendcg isn't released to pip yet.
the version of master branch should be `2.3.2`, please check your installation.
