### ISSUE TITLE
Tree with no split

### ISSUE THREAD

**Issue by PenK0Nn** [microsoft/LightGBM#2858]
I'm trying to export trainmodel(booster) to pmml format and found the inconsistency in exporting. If the booster contain  empty tree like this

Tree=2040
num_leaves=1
num_cat=0
split_feature=
split_gain=
threshold=
decision_type=
left_child=
right_child=
leaf_value=0
leaf_weight=
leaf_count=
internal_value=
internal_weight=
internal_count=
shrinkage=1

I manually remove this tree, however, I wasn't able to reload the booster back 
 lgbm.Booster(model_file=my_filename).

Is there a proper way to drop three with no split from booster?
## Environment info

Operating System: MAC

CPU/GPU model: 10.14.3

C++/Python/R version: Python

LightGBM version or commit hash:

## Error message
booster to pmml error:

Exception in thread "main" java.lang.NullPointerException
	at org.jpmml.lightgbm.LightGBMUtil.parseStringArray(LightGBMUtil.java:100)
	at org.jpmml.lightgbm.LightGBMUtil.parseIntArray(LightGBMUtil.java:111)
	at org.jpmml.lightgbm.Section.getIntArray(Section.java:62)
	at org.jpmml.lightgbm.Tree.load(Tree.java:79)
	at org.jpmml.lightgbm.GBDT.load(GBDT.java:122)
	at org.jpmml.lightgbm.LightGBMUtil.loadGBDT(LightGBMUtil.java:53)
	at org.jpmml.lightgbm.LightGBMUtil.loadGBDT(LightGBMUtil.java:45)
	at org.jpmml.lightgbm.Main.run(Main.java:125)
	at org.jpmml.lightgbm.Main.main(Main.java:118)

Manually remove tree error:
[LightGBM] [Warning] Model format error, expect a tree here. met end of trees
[LightGBM] [Fatal] Model format error, expect a tree here. met end of trees
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: Model format error, expect a tree here. met end of trees

## Steps to reproduce

1.
2.
3.

**Comment by guolinke** [comment]
you should remove the `tree_size` field too, when manually edit model file.
