### ISSUE TITLE
LightGBM GPU win10 pip install

### ISSUE THREAD

**Issue by acmilannesta** [microsoft/LightGBM#3042]
I tried to follow the guidelines to build python package based on https://github.com/microsoft/LightGBM/tree/master/python-package.

I've already installed vs2019, cmake 3.17.2 and boost 1.73.0-msvc-14.2-64.exe. 

Python version is 3.6.8 

```
pip install lightgbm --install-option=--gpu --install-option="--boost-dir=d:/boost_1_73_0" --install-option="--boost-librarydir=d:/boost_1_73_0/lib64-msvc-14.2"
```

It gives the following error

```
    ERROR: Command errored out with exit status 1:
     command: 'd:\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\chest\\AppData\\Local\\Temp\\pip-install-rsk81qed\\lightgbm\\setup.py'"'"'; __file__='"'"'C:\\Users\\chest\\AppData\\Local\\Temp\\pip-install-rsk81qed\\lightgbm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\chest\AppData\Local\Temp\pip-record-8v2a16nb\install-record.txt' --single-version-externally-managed --compile --install-headers 'd:\python36\Include\lightgbm' --gpu --boost-dir=d:/boost_1_73_0 --boost-librarydir=d:/boost_1_73_0/lib64-msvc-14.2
         cwd: C:\Users\chest\AppData\Local\Temp\pip-install-rsk81qed\lightgbm\
    Complete output (23 lines):
    running install
    INFO:LightGBM:Starting to compile the library.
    INFO:LightGBM:Starting to compile with Visual Studio 16 2019.
    INFO:LightGBM:Starting to compile with Visual Studio 15 2017.
    INFO:LightGBM:Starting to compile with Visual Studio 14 2015.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\chest\AppData\Local\Temp\pip-install-rsk81qed\lightgbm\setup.py", line 345, in <module>
        'Topic :: Scientific/Engineering :: Artificial Intelligence'])
      File "d:\python36\lib\site-packages\setuptools\__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "d:\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "d:\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "d:\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\chest\AppData\Local\Temp\pip-install-rsk81qed\lightgbm\setup.py", line 272, in run
        nomp=self.nomp, bit32=self.bit32)
      File "C:\Users\chest\AppData\Local\Temp\pip-install-rsk81qed\lightgbm\setup.py", line 164, in compile_cpp
        LOG_NOTICE)))
    Exception: Please install Visual Studio or MS Build and all required dependencies first
    The full version of error log was saved into C:\Users\chest\LightGBM_compilation.log
```

**Comment by StrikerRUS** [comment]
Hi @acmilannesta !

Have you installed `OpenCL`?

Please post `C:\Users\chest\LightGBM_compilation.log` here.

**Comment by acmilannesta** [comment]
Yes, I've installed CUDA toolkit and OpenCL is included. 

Here is the log file

```
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.25.28614.0
-- The CXX compiler identification is MSVC 19.25.28614.0
-- Check for working C compiler: D:/Microsoft VS/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: D:/Microsoft VS/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/Microsoft VS/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: D:/Microsoft VS/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -openmp (found version "2.0") 
-- Found OpenMP_CXX: -openmp (found version "2.0") 
-- Found OpenMP: TRUE (found version "2.0")  
-- Looking for CL_VERSION_2_2
-- Looking for CL_VERSION_2_2 - not found
-- Looking for CL_VERSION_2_1
-- Looking for CL_VERSION_2_1 - not found
-- Looking for CL_VERSION_2_0
-- Looking for CL_VERSION_2_0 - not found
-- Looking for CL_VERSION_1_2
-- Looking for CL_VERSION_1_2 - found
-- Found OpenCL: D:/CUDA10.1/lib/x64/OpenCL.lib (found version "1.2") 
-- OpenCL include directory: D:/CUDA10.1/include
CMake Error at D:/cmake-3.17.2-win64-x64/cmake-3.17.2-win64-x64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:164 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem system)
  (Required is at least version "1.56.0")
Call Stack (most recent call first):
  D:/cmake-3.17.2-win64-x64/cmake-3.17.2-win64-x64/share/cmake-3.17/Modules/FindPackageHandleStandardArgs.cmake:445 (_FPHSA_FAILURE_MESSAGE)
  D:/cmake-3.17.2-win64-x64/cmake-3.17.2-win64-x64/share/cmake-3.17/Modules/FindBoost.cmake:2162 (find_package_handle_standard_args)
  CMakeLists.txt:100 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/chest/AppData/Local/Temp/pip-install-ldlya_n7/lightgbm/build_cpp/CMakeFiles/CMakeOutput.log".
See also "C:/Users/chest/AppData/Local/Temp/pip-install-ldlya_n7/lightgbm/build_cpp/CMakeFiles/CMakeError.log".
CMake Error at CMakeLists.txt:7 (PROJECT):
  Generator

    Visual Studio 15 2017

  could not find any instance of Visual Studio.



-- Configuring incomplete, errors occurred!
See also "C:/Users/chest/AppData/Local/Temp/pip-install-ldlya_n7/lightgbm/build_cpp/CMakeFiles/CMakeOutput.log".
-- Selecting Windows SDK version  to target Windows 10.0.18363.
CMake Error at CMakeLists.txt:7 (PROJECT):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    The system cannot find the file specified



-- Configuring incomplete, errors occurred!
See also "C:/Users/chest/AppData/Local/Temp/pip-install-ldlya_n7/lightgbm/build_cpp/CMakeFiles/CMakeOutput.log".
```

**Comment by StrikerRUS** [comment]
Here is the root cause:
```
  Could NOT find Boost (missing: Boost_INCLUDE_DIR filesystem system)
```

Please double check your Boost installation. And then try provide missing folder directly via `--install-option="--boost-include-dir=..."` or change `--boost-dir` option in your command to `--boost-root`.

**Comment by acmilannesta** [comment]
Thanks. Just solved. I reinstalled visual studio to my system C: drive instead of D: drive. Any idea why? Even though before I put MSBuild into environmental variable.

**Comment by StrikerRUS** [comment]
Hmm, I have no idea why changing installation drive resulted in a successful try... Because CMake was able to find compilers at `D:`. Maybe VS is a software that cannot work properly when installed at non-system drive.

Anyway, I'm glad your problem has been resolved! Thanks for keeping us with updates!
