### ISSUE TITLE
GPU Error with 'max_bin'

### ISSUE THREAD

**Issue by UlionTse** [microsoft/LightGBM#3207]
When set `max_bin>255`:
```
/install/anaconda3/lib/python3.7/site-packages/lightgbm/engine.py:150: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
/install/anaconda3/lib/python3.7/site-packages/lightgbm/basic.py:1536: UserWarning: Using categorical_feature in Dataset.
  warnings.warn('Using categorical_feature in Dataset.')
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 3584
[LightGBM] [Info] Number of data points in the train set: 40695732, number of used features: 25
[LightGBM] [Info] Using requested OpenCL platform 0 device 1
[LightGBM] [Fatal] bin size 2946 cannot run on GPU
Traceback (most recent call last):
  File "base_model_gpu_v1.py", line 240, in <module>
    m_lgb = train_model(train_data,valid_data) 
  File "base_model_gpu_v1.py", line 140, in train_model
    m_lgb = lgb.train(params, train_data, valid_sets = [valid_data], verbose_eval=50)
  File "/install/anaconda3/lib/python3.7/site-packages/lightgbm/engine.py", line 230, in train
    booster = Booster(params=params, train_set=train_set)
  File "/install/anaconda3/lib/python3.7/site-packages/lightgbm/basic.py", line 1976, in __init__
    ctypes.byref(self.handle)))
  File "/install/anaconda3/lib/python3.7/site-packages/lightgbm/basic.py", line 55, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: bin size 2946 cannot run on GPU
```

When set `max_bin=255`:
```
/install/anaconda3/lib/python3.7/site-packages/lightgbm/engine.py:150: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[LightGBM] [Info] This is the GPU trainer!!
[LightGBM] [Info] Total Bins 1898
[LightGBM] [Info] Number of data points in the train set: 40695732, number of used features: 25
[LightGBM] [Info] Using requested OpenCL platform 0 device 1
[LightGBM] [Info] Using GPU Device: TITAN RTX, Vendor: NVIDIA Corporation
[LightGBM] [Info] Compiling OpenCL Kernel with 256 bins...
[LightGBM] [Info] GPU programs have been built
[LightGBM] [Info] Size of histogram bin entry: 8
[LightGBM] [Info] 16 dense feature groups (620.97 MB) transferred to GPU in 0.544184 secs. 1 sparse feature groups
[LightGBM] [Info] Start training from score 0.312323
[LightGBM] [Fatal] Check failed: (best_split_info.left_count) > (0) at /install/LightGBM/src/treelearner/serial_tree_learner.cpp, line 628 .

Traceback (most recent call last):
  File "base_model_gpu_v1.py", line 242, in <module>
    m_lgb = train_model(train_data,valid_data) 
  File "base_model_gpu_v1.py", line 139, in train_model
    m_lgb = lgb.train(params, train_data, valid_sets = [valid_data], verbose_eval=50)
  File "/install/anaconda3/lib/python3.7/site-packages/lightgbm/engine.py", line 251, in train
    booster.update(fobj=fobj)
  File "/install/anaconda3/lib/python3.7/site-packages/lightgbm/basic.py", line 2357, in update
    ctypes.byref(is_finished)))
  File "/install/anaconda3/lib/python3.7/site-packages/lightgbm/basic.py", line 55, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: Check failed: (best_split_info.left_count) > (0) at /install/LightGBM/src/treelearner/serial_tree_learner.cpp, line 628 .
```
When `max_bin in (64,128)`:
OK!

Like #1116, but 3 years have passed, isn't there a better solution? 
@guolinke You say `GPU version cannot support categorical features with high cardinality.
You can fix it by split one categorical feature into multi categorical features.` What is number with `high cardinality`?  2?

What is standard toward `high cardinality` and `max_bin`? 
Thx.

**Comment by guolinke** [comment]
If you set `max_bin` < 255 can work, I don't think the problem is from categorical features.

**Comment by UlionTse** [comment]
@guolinke  I use all numeric features to work it, category features with gpu doesn't work. So I do not know What is number with `high cardinality` of category feature?  With all numeric features,  I also don't know what is number with `max_bin` can work.

**Comment by guolinke** [comment]
@UlionTse set `high cardinality <= 256 (max_bin)`  should work. 
for the `Check failed: (best_split_info.left_count) > (0)`, it is a bug of current GPU implementation. So if you use small `max_bin` can work, you can use that temporarily.
