### ISSUE TITLE
Refit segfaults on large data sets

### ISSUE THREAD

**Issue by jtilly** [microsoft/LightGBM#3227]
Refit segfaults on large data sets, because

https://github.com/microsoft/LightGBM/blob/9f367d11ad52ae8f2f1cf7b3447735723281d820/src/c_api.cpp#L348

limits the index to be of type int32. With `n_estimators=100` this means you'll run into trouble if you're refitting with a little more than 20 million rows (arguably very large values for a refit).

The simplest fix would be to recast `i * ncol + j`, e.g.

```c++
static_cast<size_t>(i) * static_cast<size_t>(ncol) + static_cast<size_t>(j)
```

I'm happy to submit a PR.

Relevant bits of the backtrace:

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==27968==ERROR: AddressSanitizer: SEGV on unknown address 0x7f2fd8ef7800 (pc 0x7f3ef7ed5e4d bp 0x7ffcd3fe60a0 sp 0x7ffcd3fe5ea0 T0)
==27968==The signal is caused by a READ memory access.
    #0 0x7f3ef7ed5e4c in LightGBM::Booster::Refit(int const*, int, int) /home/jtilly/LightGBM/src/c_api.cpp:348
    #1 0x7f3ef7ee9bf9 in LGBM_BoosterRefit /home/jtilly/LightGBM/src/c_api.cpp:1573
    #2 0x7f3f1500762f in ffi_call_unix64 (/opt/conda/envs/lightgbm-dev/lib/python3.8/lib-dynload/../../libffi.so.6+0x662f)
   ...
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/jtilly/LightGBM/src/c_api.cpp:348 in LightGBM::Booster::Refit(int const*, int, int)
==27968==ABORTING
```

**Comment by StrikerRUS** [comment]
@jtilly Thanks a lot for finding and fixing the issue!
