### ISSUE TITLE
GPU error

### ISSUE THREAD

**Issue by ucasiggcas** [microsoft/LightGBM#3696]
```
params = {
    'task': 'train',
    'boosting_type': 'gbdt',
    'objective': 'binary',
    'metric': {'binary_logloss'},
    'num_leaves': 63,
	'num_trees': 100,
    'learning_rate': 0.01,
    'feature_fraction': 0.9,
    'bagging_fraction': 0.8,
    'bagging_freq': 5,
    'verbose': 0,
    #num_threads = 16,
    "device":"gpu"
}
```

```
/data/logs/xulm1/myconda/lib/python3.7/site-packages/lightgbm/engine.py:151: UserWarning: Found `num_trees` in params. Will use it instead of argument
  warnings.warn("Found `{}` in params. Will use it instead of argument".format(alias))
[LightGBM] [Fatal] GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
Traceback (most recent call last):
  File "../examples/binary_classification/GBFT+LR_simple.py", line 54, in <module>
    valid_sets=lgb_train)
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/lightgbm/engine.py", line 231, in train
    booster = Booster(params=params, train_set=train_set)
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/lightgbm/basic.py", line 2061, in __init__
    ctypes.byref(self.handle)))
  File "/data/logs/xulm1/myconda/lib/python3.7/site-packages/lightgbm/basic.py", line 55, in _safe_call
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: GPU Tree Learner was not enabled in this build.
Please recompile with CMake option -DUSE_GPU=1
```

## How you are using LightGBM?

LightGBM component: 

## Environment info

Operating System:

CPU/GPU model:1080

C++ compiler version:gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

CMake version:cmake version 3.18.4

Java version:

Python version:Python 3.7.9

R version:

Other:

LightGBM version or commit hash:

## Steps to reproduce

1.
2.
3.

**Comment by StrikerRUS** [comment]
Please install GPU version of LightGBM to utilize your graphic card: https://github.com/microsoft/LightGBM/tree/master/python-package#build-gpu-version.
