### ISSUE TITLE
bin size 257 cannot run on GPU

### ISSUE THREAD

**Issue by pseudotensor** [microsoft/LightGBM#4082]
I know there are a couple other issues that mention this problem, but it's gotten messy with suggestions it's related to categorical_feature setting and other stuff. Here is clean MRE.

d9a96c90cb479cef87047ba20517d97982b563eb

[lgb257.pkl.zip](https://github.com/microsoft/LightGBM/files/6166235/lgb257.pkl.zip)

```
import pickle
params = {'boosting_type': 'gbdt', 'class_weight': None, 'colsample_bytree': 0.8, 'importance_type': 'gain',
          'learning_rate': 0.5, 'max_depth': 6, 'min_child_samples': 1, 'min_child_weight': 1.0, 'min_split_gain': 0.0,
          'n_estimators': 100, 'n_jobs': 8, 'num_leaves': 64, 'objective': 'binary', 'random_state': 1234,
          'reg_alpha': 0.0, 'reg_lambda': 1.0, 'silent': True, 'subsample': 0.7, 'subsample_for_bin': 200000,
          'subsample_freq': 1, 'pred_gap': None, 'pred_periods': None, 'max_bin': 255, 'scale_pos_weight': 1.0,
          'max_delta_step': 0.0, 'min_data_in_bin': 1, 'seed': 1234, 'early_stopping_limit': None, 'device_type': 'gpu',
          'gpu_device_id': 0, 'gpu_platform_id': 0, 'gpu_use_dp': True, 'feature_fraction_seed': 1235,
          'bagging_seed': 1236, 'num_threads': 8, 'num_class': 1, 'verbose': -1, 'categorical_feature': ''}
model, X, y, kwargs = pickle.load(open(lgb257.pkl, "rb"))
model.fit(X, y, **kwargs)
```

```
[LightGBM] [Warning] num_threads is set=8, n_jobs=8 will be ignored. Current value: num_threads=8
[LightGBM] [Warning] seed is set=1234, random_state=1234 will be ignored. Current value: seed=1234
/home/jon/minicondadai/lib/python3.6/site-packages/lightgbm_gpu/basic.py:1586: UserWarning: Using categorical_feature in Dataset.
  warnings.warn('Using categorical_feature in Dataset.')
/home/jon/minicondadai/lib/python3.6/site-packages/lightgbm_gpu/basic.py:1590: UserWarning: categorical_feature in Dataset is overridden.
New categorical_feature is []
  'New categorical_feature is {}'.format(sorted(list(categorical_feature))))
/home/jon/minicondadai/lib/python3.6/site-packages/lightgbm_gpu/basic.py:1108: UserWarning: categorical_feature keyword has been found in `params` and will be ignored.
Please use categorical_feature argument of the Dataset constructor to pass this parameter.
  .format(key))
[LightGBM] [Fatal] bin size 257 cannot run on GPU
Traceback (most recent call last):
  File "/home/jon/h2oai.fullcondatest/h2oaicore/lgb257.py", line 18, in <module>
    model.fit(X, y, **kwargs)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/lightgbm_gpu/sklearn.py", line 867, in fit
    callbacks=callbacks, init_model=init_model)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/lightgbm_gpu/sklearn.py", line 637, in fit
    callbacks=callbacks, init_model=init_model)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/lightgbm_gpu/engine.py", line 230, in train
    booster = Booster(params=params, train_set=train_set)
  File "/home/jon/minicondadai/lib/python3.6/site-packages/lightgbm_gpu/basic.py", line 2104, in __init__
    ctypes.byref(self.handle)))
  File "/home/jon/minicondadai/lib/python3.6/site-packages/lightgbm_gpu/basic.py", line 52, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: bin size 257 cannot run on GPU

```

**Comment by pseudotensor** [comment]
Here is more minimal MRE:

```
import pickle
X, y = pickle.load(open("/home/jon/lgb257b.pkl", "rb"))

params = dict(categorical_feature='', device_type='gpu', gpu_device_id=0, gpu_platform_id=0, gpu_use_dp=True, min_data_in_bin=1)
model = lgb.LGBMClassifier(**params)
model.fit(X, y, categorical_feature='')
```

That is, I iterated through all parameters, the key to failure is (of course) on GPU but also min_data_in_bin=1.

[lgb257b.pkl.zip](https://github.com/microsoft/LightGBM/files/6166360/lgb257b.pkl.zip)

**Comment by pseudotensor** [comment]
Hi, any thoughts?  Seems like a clear MRE, but it's been 5 days and no response.  Thanks.

**Comment by pseudotensor** [comment]
@guolinke ?

**Comment by pseudotensor** [comment]
```
  File "/opt/h2oai/dai/python/lib/python3.8/site-packages/lightgbm_gpu/sklearn.py", line 712, in fit
    self._Booster = train(params, train_set,
  File "/opt/h2oai/dai/python/lib/python3.8/site-packages/lightgbm_gpu/engine.py", line 235, in train
    booster = Booster(params=params, train_set=train_set)
  File "/opt/h2oai/dai/python/lib/python3.8/site-packages/lightgbm_gpu/basic.py", line 2528, in __init__
    _safe_call(_LIB.LGBM_BoosterCreate(
  File "/opt/h2oai/dai/python/lib/python3.8/site-packages/lightgbm_gpu/basic.py", line 125, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: bin size 258 cannot run on GPU
```

Again,  no categorical handling enabled etc.

**Comment by arnocandel** [comment]
@guolinke reminder - still the dominant failure mode for LightGBM in Driverless AI

**Comment by shiyu1994** [comment]
@pseudotensor The current CUDA version is doing the correct thing, it can handle categorical features normally. The only problem is current implementation only do histogram construction on GPU, so the GPU utilization can be low.

Supporting of categorical features is not added yet in our first part of new CUDA version #4630, but will be added later.

**Comment by arnocandel** [comment]
Here's another minimal repro, in case helps

[lgb.bin257.pkl.zip](https://github.com/microsoft/LightGBM/files/7628254/lgb.bin257.pkl.zip)

```
import pickle
import lightgbm as lgb
print(lgb.__version__)

from lightgbm.sklearn import LGBMRegressor
with open("lgb.bin257.pkl", "rb") as f:
    X, y = pickle.load(f)
    model = LGBMRegressor(max_bin=252, device_type='gpu')
    model.fit(X, y)
    print("OK1")

    model = LGBMRegressor(max_bin=253, device_type='gpu')
    model.fit(X, y)
    print("OK2")
```

first one passes, second one fails, not sure where 257 comes from:
```
/home/arno/minicondadai_py38/bin/python /nfs4/lgb_prefit_1c95733f-58d6-4a61-969f-b2331e03e895.py -m h2oai
3.2.1.99
OK1
[LightGBM] [Fatal] bin size 257 cannot run on GPU
Traceback (most recent call last):
  File "/nfs4/lgb_prefit_1c95733f-58d6-4a61-969f-b2331e03e895.py", line 13, in <module>
    model.fit(X, y)
  File "/home/arno/minicondadai_py38/lib/python3.8/site-packages/lightgbm/sklearn.py", line 851, in fit
    super().fit(X, y, sample_weight=sample_weight, init_score=init_score,
  File "/home/arno/minicondadai_py38/lib/python3.8/site-packages/lightgbm/sklearn.py", line 714, in fit
    self._Booster = train(params, train_set,
  File "/home/arno/minicondadai_py38/lib/python3.8/site-packages/lightgbm/engine.py", line 260, in train
    booster = Booster(params=params, train_set=train_set)
  File "/home/arno/minicondadai_py38/lib/python3.8/site-packages/lightgbm/basic.py", line 2537, in __init__
    _safe_call(_LIB.LGBM_BoosterCreate(
  File "/home/arno/minicondadai_py38/lib/python3.8/site-packages/lightgbm/basic.py", line 125, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: bin size 257 cannot run on GPU

Process finished with exit code 1
```

**Comment by jameslamb** [comment]
Thanks very much @arnocandel !

But are you able to provide a reproducible example starting from raw data in a text-based format, generated from scratch with `pandas` / `numpy` / `scipy` code, or using a widely-distributed dataset like those available in `sklearn.datasets`?

I personally don't ever load pickle files whose origin I don't know, and I expect others wanting to contribute to fixing this issue might share that hesistation.

From https://docs.python.org/3/library/pickle.html

> Warning The `pickle` module is not secure. Only unpickle data you trust.

> It is possible to construct malicious pickle data which will execute arbitrary code during unpickling. Never unpickle data that could have come from an untrusted source, or that could have been tampered with.

**Comment by arnocandel** [comment]
[X_y.zip](https://github.com/microsoft/LightGBM/files/7817145/X_y.zip)

**Comment by lewis-morris** [comment]
I'm having the same issue over here! 

```bin size 257 cannot run on GPU```

**Comment by arnocandel** [comment]
@jameslamb - were you able to check with above two .csv files for X and y?

**Comment by jameslamb** [comment]
> were you able to check with above two .csv files for X and y

I was not. If you're subscribed to this issue, you'll be notified when someone picks this up or has new information to share.

**Comment by jiluojiluo** [comment]
this is a bug for lightGBM for GPU,when use CPU,it is OK.

**Comment by ahmedshahriar** [comment]
Any update so far on this issue?

**Comment by lilianabs** [comment]
I'm having the same issue :(

**Comment by holma91** [comment]
Still have this issue.

**Comment by matousfamera** [comment]
I have the same issue

"LightGBMError: bin size 1973 cannot run on GPU."

It runs alright using CPU.

**Comment by shiyu1994** [comment]
For everyone who encounters this issue with the `-DUSE_GPU=ON` version of LightGBM, please check our latest GPU version which should be compiled with `-DUSE_CUDA=ON`.
https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-cuda-version. Thanks.

**Comment by cocoderss** [comment]
> For everyone who encounters this issue with the `-DUSE_GPU=ON` version of LightGBM, please check our latest GPU version which should be compiled with `-DUSE_CUDA=ON`. https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-cuda-version. Thanks.

I have followed these instructions to install the CUDA version instead of the GPU version, but I still have the same issue:
`LightGBMError: bin size XXX cannot run on GPU.`

For more info, I am running on a linux server with cuda 12.1 with A100. Let me know if more info are needed to fix this issue.

**Comment by wil70** [comment]
Same issue, works fine on CPU
**[LightGBM] [Fatal] bin size 260 cannot run on GPU**

**Comment by cocoderss** [comment]
> For everyone who encounters this issue with the `-DUSE_GPU=ON` version of LightGBM, please check our latest GPU version which should be compiled with `-DUSE_CUDA=ON`. https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#build-cuda-version. Thanks.


I have realized that after compiling lightgbm with the cuda option, and then using the command `sudo sh ./build-python.sh install --precompile` to install it as highlighted in [the documentation](https://lightgbm.readthedocs.io/en/latest/GPU-Tutorial.html#install-python-interface-optional), it defaults to installing the pip repo version. I have not verified that by inspecting the `build-python.sh` script, but  my workaround was to build the pip wheel package myself. This solves the issue, and when specifying `device_type=cuda` works correctly as expected.     

On a side note, the main issue of cuda memory still persists, and this relates to the fact that a categorical feature has too many unique values (I tested by omitting that feature and it works fine on both gpu, cuda and cpu). But when including that feature, using the gpu version I get `LightGBMError: bin size XXX cannot run on GPU`, it works fine on the CPU, but takes a very long time, and using the cuda version, you can find the error below (optuna study multiple workers). 

```
[LightGBM] [Fatal] [CUDA] an illegal memory access was encountered /home/user/notebooks/jupiter/tmp/src/io/cuda/cuda_column_data.cpp 67

[LightGBM] [Fatal] [CUDA] an illegal memory access was encountered /home/user/notebooks/jupiter/tmp/src/treelearner/cuda/cuda_best_split_finder.cu 2066

[LightGBM] [Fatal] [CUDA] an illegal memory access was encountered /home/user/notebooks/jupiter/tmp/src/io/cuda/cuda_column_data.cpp 67

[LightGBM] [Warning] [CUDA] an illegal memory access was encountered /home/user/notebooks/jupiter/tmp/src/io/cuda/cuda_column_data.cpp 67

[LightGBM] [Warning] [CUDA] an illegal memory access was encountered /home/user/notebooks/jupiter/tmp/src/io/cuda/cuda_column_data.cpp 67

[LightGBM] [Fatal] [CUDA] an illegal memory access was encountered /home/user/notebooks/jupiter/tmp/src/io/cuda/cuda_column_data.cpp 67

[LightGBM] [Fatal] [CUDA] an illegal memory access was encountered /home/user/notebooks/jupiter/tmp/src/io/cuda/cuda_tree.cpp 37

[LightGBM] [Warning] [CUDA] an illegal memory access was encountered /home/user/notebooks/jupiter/tmp/src/io/cuda/cuda_column_data.cpp 67

[LightGBM] [Fatal] [CUDA] an illegal memory access was encountered /home/user/notebooks/jupiter/tmp/src/io/cuda/cuda_column_data.cpp 67

terminate called after throwing an instance of 'std::runtime_error'
[LightGBM] [Warning] [CUDA] an illegal memory access was encountered /home/user/notebooks/jupiter/tmp/src/io/cuda/cuda_column_data.cpp 67

  what():  [CUDA] an illegal memory access was encountered /home/user/notebooks/jupiter/tmp/src/io/cuda/cuda_tree.cpp 37

[LightGBM] [Fatal] [CUDA] an illegal memory access was encountered /home/user/notebooks/jupiter/tmp/src/io/cuda/cuda_column_data.cpp 67

[LightGBM] [Warning] [CUDA] an illegal memory access was encountered /home/user/notebooks/jupiter/tmp/src/io/cuda/cuda_column_data.cpp 67
```


So it seems that there is a limitation in the implementation when it comes to categorical features on cuda/gpu, that requires a fix.

**Comment by yuhorun** [comment]
I have the same issue

"LightGBMError: bin size 512 cannot run on GPU."
