### ISSUE TITLE
 but /Users/hyy/Library/Python/2.7/lib/python/site-packages is being added to sys.path

### ISSUE THREAD

**Issue by hyy1101** [Microsoft/LightGBM#467]
when i do this:
`cd /Users/hyy/Downloads/LightGBM-master/python-package` and  `python setup.py install`

it will show me : 
```
/usr/local/lib/python2.7/site-packages/distribute-0.6.28-py2.7.egg/setuptools/command/install_scripts.py:3: UserWarning: Module backports was already imported from None, but /Users/hyy/Library/Python/2.7/lib/python/site-packages is being added to sys.path
  from pkg_resources import Distribution, PathMetadata, ensure_directory
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    LIB_PATH = [os.path.relpath(path, CURRENT_DIR) for path in libpath['find_lib_path']()]
  File "lightgbm/libpath.py", line 29, in find_lib_path
    raise Exception('Cannot find lightgbm Library in following paths: ' + ','.join(dll_path))
Exception: Cannot find lightgbm Library in following paths: /Users/hyy/Downloads/LightGBM-master/python-package/lightgbm/lib_lightgbm.so,/Users/hyy/Downloads/LightGBM-master/lib/lib_lightgbm.so,/Users/hyy/Downloads/LightGBM-master/lib_lightgbm.so,/Users/hyy/Downloads/LightGBM-master/python-package/lightgbm/lib/lib_lightgbm.so,/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lightgbm/lib_lightgbm.so
```

**how should I do, thank you!**

**Comment by guolinke** [comment]
@hyy1101 
you should build the lightgbm binaries first.

**Comment by hyy1101** [comment]
how to  build the lightgbm binaries?

**Comment by guolinke** [comment]
https://github.com/Microsoft/LightGBM/tree/master/python-package#installation
