### ISSUE TITLE
Crash without warning or error message when using Dataset object

### ISSUE THREAD

**Issue by weipenegHU** [microsoft/LightGBM#4789]
## Description

I used a lightGBM dataset object to load the training data which was about 3 GB, but the jupyter notebook crashed without showing any warning or error messages during the training phrase (crashed during the first iteration). However, if I use pandas to load the dataset, the training can proceed successfully. This crash happened both in the kaggle kernel and the local environment.
## Reproducible example

```
import pandas as pd
import lightgbm as lgbm
import numpy as np
import sklearn
import optuna


X_train = lgbm.Dataset("X_train.csv")
y_train = pd.read_csv("y_train.csv")
X_valid = lgbm.Dataset("X_valid.csv")
y_valid = pd.read_csv("y_valid.csv")


def objective(trial):
  dtrain = lgbm.Dataset("X_train.csv", label=y_train)
  dvalid = lgbm.Dataset("X_valid.csv", label=y_valid)
  param = {
      "objective": "regression",
      "metric": ["rmse"],
      "verbosity": -1,
      "num_leaves": trial.suggest_int("num_leaves", 500,1000, step=5),
      "cat_smooth": trial.suggest_float("cat_smooth",10,50, log=True),
      "min_child_samples": trial.suggest_int("min_child_samples",10,30),
      "min_child_weight": trial.suggest_float("min_child_weight",0.01,0.05, log=True),
      "max_bin": trial.suggest_int("max_bin", 100,230,log=True),
      "learning_rate": trial.suggest_float("learning_rate",0.001,1,log=True),
      "subsample_for_bin": trial.suggest_int("subsample_for_bin", 100000,310000,log=True),
      "min_data_in_bin": trial.suggest_int("min_data_in_bin",5,11,step=1),
      "colsample_bytree": trial.suggest_float("colsample_bytree",0.6,1,log=True),
      "subsample": trial.suggest_float("subsample",0.5,1,log=True),
      "subsample_freq": trial.suggest_int("subsample_freq",5,20),
      "num_iterations": trial.suggest_int("num_iterations",5000,10000,step=100),
      'early_stopping_round':10
  }
  
  pruning_callback = optuna.integration.LightGBMPruningCallback(trial, "rmse")
  gbm = lgbm.train(param, dtrain,valid_sets=[dvalid], verbose_eval=False, callbacks=[pruning_callback])
  preds = gbm.predict(X_valid)
  mse = sklearn.metrics.mean_squared_error(y_valid, preds)
  return mse


study = optuna.create_study(pruner=optuna.pruners.MedianPruner(n_warmup_steps=10), direction="minimize")
study.optimize(objective, n_trials=1000)

```
LightGBM version or commit hash: 3.2.1

Command(s) you used to install LightGBM

```shell

```pip install lightGBM

<!-- Put any additional environment information here -->


## Additional Comments
<!-- What else should we know? -->

**Comment by shiyu1994** [comment]
@weipenegHU Thanks for using LightGBM. Could you please set `verbosity` to `2` and run your code snippet in terminal instead of jupyter to check if there's any informative output?
In addition, it would be appreciated if a reproducible example can be provided to demonstrate your problem.

**Comment by shiyu1994** [comment]
Also, we have some bug fixes contained in our latest release 3.3.0 or 3.3.1. You may try with the latest version.

**Comment by weipenegHU** [comment]
> @weipenegHU Thanks for using LightGBM. Could you please set `verbosity` to `2` and run your code snippet in terminal instead of jupyter to check if there's any informative output? In addition, it would be appreciated if a reproducible example can be provided to demonstrate your problem.

Sample data for repeating the problem [sample_data.zip](https://github.com/microsoft/LightGBM/files/7518387/sample_data.zip)
Please check the output:
```
[I 2021-11-11 14:29:07,645] A new study created in memory with name: no-name-3580608e-03ce-4c60-9a36-b32db1143b76
E:\Anaconda3\lib\site-packages\lightgbm\engine.py:148: UserWarning: Found `num_iterations` in params. Will use it instead of argument
  _log_warning("Found `{}` in params. Will use it instead of argument".format(alias))
E:\Anaconda3\lib\site-packages\lightgbm\engine.py:153: UserWarning: Found `early_stopping_round` in params. Will use it instead of argument
  _log_warning("Found `{}` in params. Will use it instead of argument".format(alias))
[LightGBM] [Fatal] Unknown token date_block_num in data file
[W 2021-11-11 14:29:07,882] Trial 0 failed because of the following error: LightGBMError('Unknown token date_block_num in data file')
Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\optuna\study\_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File ".\predict_sales.py", line 44, in objective
    gbm = lgbm.train(param, dtrain,valid_sets=[dvalid], verbose_eval=False, callbacks=[pruning_callback])
  File "E:\Anaconda3\lib\site-packages\lightgbm\engine.py", line 228, in train
    booster = Booster(params=params, train_set=train_set)
  File "E:\Anaconda3\lib\site-packages\lightgbm\basic.py", line 2229, in __init__
    train_set.construct()
  File "E:\Anaconda3\lib\site-packages\lightgbm\basic.py", line 1468, in construct
    self._lazy_init(self.data, label=self.label,
  File "E:\Anaconda3\lib\site-packages\lightgbm\basic.py", line 1260, in _lazy_init
    _safe_call(_LIB.LGBM_DatasetCreateFromFile(
  File "E:\Anaconda3\lib\site-packages\lightgbm\basic.py", line 110, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: Unknown token date_block_num in data file
Traceback (most recent call last):
  File ".\predict_sales.py", line 51, in <module>
    study.optimize(objective, n_trials=1000)
  File "E:\Anaconda3\lib\site-packages\optuna\study\study.py", line 400, in optimize
    _optimize(
  File "E:\Anaconda3\lib\site-packages\optuna\study\_optimize.py", line 66, in _optimize
    _optimize_sequential(
  File "E:\Anaconda3\lib\site-packages\optuna\study\_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "E:\Anaconda3\lib\site-packages\optuna\study\_optimize.py", line 264, in _run_trial
    raise func_err
  File "E:\Anaconda3\lib\site-packages\optuna\study\_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File ".\predict_sales.py", line 44, in objective
    gbm = lgbm.train(param, dtrain,valid_sets=[dvalid], verbose_eval=False, callbacks=[pruning_callback])
  File "E:\Anaconda3\lib\site-packages\lightgbm\engine.py", line 228, in train
    booster = Booster(params=params, train_set=train_set)
  File "E:\Anaconda3\lib\site-packages\lightgbm\basic.py", line 2229, in __init__
    train_set.construct()
  File "E:\Anaconda3\lib\site-packages\lightgbm\basic.py", line 1468, in construct
    self._lazy_init(self.data, label=self.label,
  File "E:\Anaconda3\lib\site-packages\lightgbm\basic.py", line 1260, in _lazy_init
    _safe_call(_LIB.LGBM_DatasetCreateFromFile(
  File "E:\Anaconda3\lib\site-packages\lightgbm\basic.py", line 110, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: Unknown token date_block_num in data file
```

**Comment by weipenegHU** [comment]
> Also, we have some bug fixes contained in our latest release 3.3.0 or 3.3.1. You may try with the latest version.

Problem still exists after upgrading to 3.3.1

**Comment by shiyu1994** [comment]
@weipenegHU, after checking the `csv` files, I found that they include the header lines. Please add `header`: `true` in your parameter, and the problem should be resolved.

**Comment by weipenegHU** [comment]
This works! Thanks a lot!
However, another problem came up. The training data and valid data both have 139 features, but the Dataset object seems to only find 138 of them in the training set. Here is the error message:
```
LightGBMError                             Traceback (most recent call last)
<ipython-input-15-ed35e1a90c8f> in <module>
      2 
      3 study = optuna.create_study(pruner=optuna.pruners.MedianPruner(n_warmup_steps=10), direction="minimize")
----> 4 study.optimize(objective, n_trials=1000)
      5 
      6 print("Number of finished trials: {}".format(len(study.trials)))

E:\Anaconda3\lib\site-packages\optuna\study\study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    398             )
    399 
--> 400         _optimize(
    401             study=self,
    402             func=func,

E:\Anaconda3\lib\site-packages\optuna\study\_optimize.py in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
     64     try:
     65         if n_jobs == 1:
---> 66             _optimize_sequential(
     67                 study,
     68                 func,

E:\Anaconda3\lib\site-packages\optuna\study\_optimize.py in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
    161 
    162         try:
--> 163             trial = _run_trial(study, func, catch)
    164         except Exception:
    165             raise

E:\Anaconda3\lib\site-packages\optuna\study\_optimize.py in _run_trial(study, func, catch)
    262 
    263     if state == TrialState.FAIL and func_err is not None and not isinstance(func_err, catch):
--> 264         raise func_err
    265     return trial
    266 

E:\Anaconda3\lib\site-packages\optuna\study\_optimize.py in _run_trial(study, func, catch)
    211 
    212     try:
--> 213         value_or_values = func(trial)
    214     except exceptions.TrialPruned as e:
    215         # TODO(mamu): Handle multi-objective cases.

<ipython-input-14-bab9be93343f> in objective(trial)
     29     pruning_callback = optuna.integration.LightGBMPruningCallback(trial, "rmse")
     30     gbm = lgbm.train(param, dtrain,valid_sets=[dvalid], verbose_eval=False, callbacks=[pruning_callback])
---> 31     preds = gbm.predict(X_valid)
     32     mse = sklearn.metrics.mean_squared_error(y_valid, preds)
     33     return mse

E:\Anaconda3\lib\site-packages\lightgbm\basic.py in predict(self, data, start_iteration, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape, **kwargs)
   3536             else:
   3537                 num_iteration = -1
-> 3538         return predictor.predict(data, start_iteration, num_iteration,
   3539                                  raw_score, pred_leaf, pred_contrib,
   3540                                  data_has_header, is_reshape)

E:\Anaconda3\lib\site-packages\lightgbm\basic.py in predict(self, data, start_iteration, num_iteration, raw_score, pred_leaf, pred_contrib, data_has_header, is_reshape)
    846             preds, nrow = self.__pred_for_csc(data, start_iteration, num_iteration, predict_type)
    847         elif isinstance(data, np.ndarray):
--> 848             preds, nrow = self.__pred_for_np2d(data, start_iteration, num_iteration, predict_type)
    849         elif isinstance(data, list):
    850             try:

E:\Anaconda3\lib\site-packages\lightgbm\basic.py in __pred_for_np2d(self, mat, start_iteration, num_iteration, predict_type)
    936             return preds, nrow
    937         else:
--> 938             return inner_predict(mat, start_iteration, num_iteration, predict_type)
    939 
    940     def __create_sparse_native(self, cs, out_shape, out_ptr_indptr, out_ptr_indices, out_ptr_data,

E:\Anaconda3\lib\site-packages\lightgbm\basic.py in inner_predict(mat, start_iteration, num_iteration, predict_type, preds)
    906                 raise ValueError("Wrong length of pre-allocated predict array")
    907             out_num_preds = ctypes.c_int64(0)
--> 908             _safe_call(_LIB.LGBM_BoosterPredictForMat(
    909                 self.handle,
    910                 ptr_data,

E:\Anaconda3\lib\site-packages\lightgbm\basic.py in _safe_call(ret)
    123     """
    124     if ret != 0:
--> 125         raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
    126 
    127 

LightGBMError: The number of features in data (139) is not the same as it was in training data (138).
You can set ``predict_disable_shape_check=true`` to discard this error, but please be aware what you are doing.
```

**Comment by shiyu1994** [comment]
Do your CSV files contain a column for label? (If so, you need to specify `label_column` to the column name in your parameters.) LightGBM will consume the first column as the label by default, when fed a CSV file for training.
Another question is what's the form of the test data you passed into the `predict` method?

**Comment by weipenegHU** [comment]
I loaded the label from csv file and passed it to the Dataset object. 
```
y_train = pd.read_csv("y_train.csv")
dtrain = lgbm.Dataset("X_train.csv", label=y_train)
```
If I specify ```label_column``` in the parameters, do I still need to pass the y_train to the Dataset object?
The test data for prediction is a pandas dataframe object.

**Comment by shiyu1994** [comment]
In that case, we have 2 choices:
1. Load `X_train.csv` into a numpy array or pandas dataframe `X_train`, and use `lgbm.Dataset(X_train, label=y_train)`.
2. Store `y_train.csv` and `X_train.csv` in the same file `train.csv`, and specify the label through `label_column`, i.e. `lgbm.Dataset('train.csv', label_column='label_column_name')` 

We cannot mix up the two ways by loading data from a file but specify label with an array.

**Comment by weipenegHU** [comment]
I successfully ran my model following your recommendation! Much obliged! 
However, I double checked the documentation about the Dataset api ("https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.Dataset.html?highlight=Dataset") before I asked this question and there was no description of how to use Dataset correctly. Maybe it is a good idea to give the documentation an update.
