### ISSUE TITLE
[LightGBM] [Fatal] Check failed: bag_data_indices_[bag_data_cnt_ - 1] > bag_data_indices_[bag_data_cnt_]

### ISSUE THREAD

**Issue by henry0312** [Microsoft/LightGBM#481]
When subsample (bagging_fraction) is almost 1.0 and the number of input data is small, the below error will occur.

## Environment info

Operating System: Ubuntu 16.04.2 (4.8.0-49-generic)
CPU:  Intel Core i7-6950X
C++/Python/R version: Python 3.5.3

## Error Message:

```
❯ python test.py
Load data...
Start training...
[1]     valid_0's l2: 0.250137
[2]     valid_0's l2: 0.247054
[3]     valid_0's l2: 0.242173
[4]     valid_0's l2: 0.241287
[5]     valid_0's l2: 0.241897
[6]     valid_0's l2: 0.240208
[7]     valid_0's l2: 0.236942
[8]     valid_0's l2: 0.237014
[9]     valid_0's l2: 0.237011
[10]    valid_0's l2: 0.235156
[11]    valid_0's l2: 0.233918
[12]    valid_0's l2: 0.2319
[LightGBM] [Fatal] Check failed: bag_data_indices_[bag_data_cnt_ - 1] > bag_data_indices_[bag_data_cnt_] at /home/henry/.ghq/github.com/Microsoft/LightGBM/src/boosting/gbdt.cpp, line 314 .

Traceback (most recent call last):
  File "test.py", line 36, in <module>
    eval_metric='l2')
  File "/home/henry/.pyenv/versions/3.5.3/lib/python3.5/site-packages/lightgbm-0.1-py3.5.egg/lightgbm/sklearn.py", line 536, in fit
    callbacks=callbacks)
  File "/home/henry/.pyenv/versions/3.5.3/lib/python3.5/site-packages/lightgbm-0.1-py3.5.egg/lightgbm/sklearn.py", line 413, in fit
    callbacks=callbacks)
  File "/home/henry/.pyenv/versions/3.5.3/lib/python3.5/site-packages/lightgbm-0.1-py3.5.egg/lightgbm/engine.py", line 180, in train
    booster.update(fobj=fobj)
  File "/home/henry/.pyenv/versions/3.5.3/lib/python3.5/site-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 1355, in update
    ctypes.byref(is_finished)))
  File "/home/henry/.pyenv/versions/3.5.3/lib/python3.5/site-packages/lightgbm-0.1-py3.5.egg/lightgbm/basic.py", line 47, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError())
lightgbm.basic.LightGBMError: b'Check failed: bag_data_indices_[bag_data_cnt_ - 1] > bag_data_indices_[bag_data_cnt_] at /home/henry/.ghq/github.com/Microsoft/LightGBM/src/boosting/gbdt.cpp, line 314 .\n'
```

## Reproducible examples

```python
import numpy
import lightgbm as lgb
import pandas as pd

# load or create your dataset
print('Load data...')
df_train = pd.read_csv('../regression/regression.train', header=None, sep='\t')
df_test = pd.read_csv('../regression/regression.test', header=None, sep='\t')

y_train = df_train[0].values[:64]
y_test = df_test[0].values
X_train = df_train.drop(0, axis=1).values[:64]
X_test = df_test.drop(0, axis=1).values

print('Start training...')
# train
gbm = lgb.LGBMRegressor(
    objective='regression',
    num_leaves=31,
    learning_rate=0.10,
    n_estimators=100,
    subsample=1.0 - 1.0e-10
)
gbm.fit(X_train, y_train,
        eval_set=[(X_test, y_test)],
        eval_metric='l2')
```

## Steps to reproduce

1. just run the above script

**Comment by henry0312** [comment]
https://github.com/Microsoft/LightGBM/commit/0bf0ec03480a5041309deb35dfa2646c1b5762d2 fixes the issue.
Thank you.
