### ISSUE TITLE
protocol.Py4JJavaError: An error occurred while calling None.com.microsoft.ml.spark.lightgbm.LightGBMClassifier.

### ISSUE THREAD

**Issue by Quentin-Song** [microsoft/LightGBM#5202]
/Users/songqingqiang/soft/anaconda3/envs/torch_38/bin/python /Users/songqingqiang/workProject/dev/xiaodan/er.py
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/Users/songqingqiang/soft/anaconda3/envs/torch_38/lib/python3.8/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
https://mmlspark.azureedge.net/maven added as a remote repository with the name: repo-1
:: loading settings :: url = jar:file:/Users/songqingqiang/soft/anaconda3/envs/torch_38/lib/python3.8/site-packages/pyspark/jars/ivy-2.5.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
Ivy Default Cache set to: /Users/songqingqiang/.ivy2/cache
The jars for the packages stored in: /Users/songqingqiang/.ivy2/jars
com.microsoft.ml.spark#mmlspark_2.11 added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent-f6a0612e-3a2b-4ca4-a459-af8cce39f77c;1.0
	confs: [default]
	found com.microsoft.ml.spark#mmlspark_2.11;1.0.0-rc1 in repo-1
	found org.scalactic#scalactic_2.11;3.0.5 in central
	found org.scala-lang#scala-reflect;2.11.12 in central
	found org.scalatest#scalatest_2.11;3.0.5 in central
	found org.scala-lang.modules#scala-xml_2.11;1.0.6 in central
	found io.spray#spray-json_2.11;1.3.2 in central
	found com.microsoft.cntk#cntk;2.4 in central
	found org.openpnp#opencv;3.2.0-1 in central
	found com.jcraft#jsch;0.1.54 in central
	found org.apache.httpcomponents#httpclient;4.5.6 in central
	found org.apache.httpcomponents#httpcore;4.4.10 in central
	found commons-logging#commons-logging;1.2 in central
	found commons-codec#commons-codec;1.10 in central
	found com.microsoft.ml.lightgbm#lightgbmlib;2.3.100 in central
	found com.github.vowpalwabbit#vw-jni;8.7.0.3 in central
:: resolution report :: resolve 228ms :: artifacts dl 7ms
	:: modules in use:
	com.github.vowpalwabbit#vw-jni;8.7.0.3 from central in [default]
	com.jcraft#jsch;0.1.54 from central in [default]
	com.microsoft.cntk#cntk;2.4 from central in [default]
	com.microsoft.ml.lightgbm#lightgbmlib;2.3.100 from central in [default]
	com.microsoft.ml.spark#mmlspark_2.11;1.0.0-rc1 from repo-1 in [default]
	commons-codec#commons-codec;1.10 from central in [default]
	commons-logging#commons-logging;1.2 from central in [default]
	io.spray#spray-json_2.11;1.3.2 from central in [default]
	org.apache.httpcomponents#httpclient;4.5.6 from central in [default]
	org.apache.httpcomponents#httpcore;4.4.10 from central in [default]
	org.openpnp#opencv;3.2.0-1 from central in [default]
	org.scala-lang#scala-reflect;2.11.12 from central in [default]
	org.scala-lang.modules#scala-xml_2.11;1.0.6 from central in [default]
	org.scalactic#scalactic_2.11;3.0.5 from central in [default]
	org.scalatest#scalatest_2.11;3.0.5 from central in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   15  |   0   |   0   |   0   ||   15  |   0   |
	---------------------------------------------------------------------
:: retrieving :: org.apache.spark#spark-submit-parent-f6a0612e-3a2b-4ca4-a459-af8cce39f77c
	confs: [default]
	0 artifacts copied, 15 already retrieved (0kB/5ms)
22/05/10 03:29:36 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
22/05/10 03:29:37 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
22/05/10 03:29:37 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
Traceback (most recent call last):
  File "/Users/songqingqiang/workProject/dev/xiaodan/er.py", line 170, in <module>
    classifier = LightGBMClassifier(
  File "/Users/songqingqiang/soft/anaconda3/envs/torch_38/lib/python3.8/site-packages/pyspark/__init__.py", line 114, in wrapper
    return func(self, **kwargs)
  File "/private/var/folders/nm/gh3n43z51j96ly6bq_xsr65r0000gn/T/spark-ab7496c9-fb3c-4dac-9e56-66a529e167fc/userFiles-1aa4113d-8fe3-4929-8836-6c91c9a06ec4/com.microsoft.ml.spark_mmlspark_2.11-1.0.0-rc1.jar/mmlspark/lightgbm/_LightGBMClassifier.py", line 66, in __init__
  File "/Users/songqingqiang/soft/anaconda3/envs/torch_38/lib/python3.8/site-packages/pyspark/ml/wrapper.py", line 66, in _new_java_obj
    return java_obj(*java_args)
  File "/Users/songqingqiang/soft/anaconda3/envs/torch_38/lib/python3.8/site-packages/py4j/java_gateway.py", line 1573, in __call__
    return_value = get_return_value(
  File "/Users/songqingqiang/soft/anaconda3/envs/torch_38/lib/python3.8/site-packages/pyspark/sql/utils.py", line 111, in deco
    return f(*a, **kw)
  File "/Users/songqingqiang/soft/anaconda3/envs/torch_38/lib/python3.8/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling None.com.microsoft.ml.spark.lightgbm.LightGBMClassifier.
: java.lang.NoClassDefFoundError: org/apache/spark/ml/util/MLWritable$class
	at com.microsoft.ml.spark.lightgbm.LightGBMClassifier.<init>(LightGBMClassifier.scala:27)
	at com.microsoft.ml.spark.lightgbm.LightGBMClassifier.<init>(LightGBMClassifier.scala:29)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:238)
	at py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
	at py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.ml.util.MLWritable$class
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 14 more

Process finished with exit code 1

**Comment by StrikerRUS** [comment]
Hey @Quentin-Song ! Sorry about the problem you've faced. But unfortunately we're not maintaining SynapseML (formerly MMLSpark) in this repo. Please address you issue to the https://github.com/microsoft/SynapseML/issues.
