### ISSUE TITLE
lightgbm.basic.LightGBMError: Out of Resources

### ISSUE THREAD

**Issue by aidiss** [microsoft/LightGBM#5214]
## Description
Using ray.tune.sklearn.TuneSearchCV to tune lightgbm.LGBMRegressor.

After 3 hours of running we get `lightgbm.basic.LightGBMError: Out of Resources` error.
We were not able to find "Resources" is referencing.

```
2022-05-15 07:00:07,538	ERROR trial_runner.py:917 -- Trial _Trainable_6df542d8: Error processing event.
Traceback (most recent call last):
    File "/opt/project/src/run.py", line 66, in <module>
      model = train(df, "Price_area", tuner, args.run_selection)
    File "/opt/project/src/main.py", line 32, in train
      model.fit(X_train, y_train, tune_params={"resources_per_trial": {"cpu": 4, "gpu": 0.5}})
    File "/opt/miniforge/lib/python3.9/site-packages/tune_sklearn/tune_basesearch.py", line 622, in fit
      return self._fit(X, y, groups, tune_params, **fit_params)
    File "/opt/miniforge/lib/python3.9/site-packages/tune_sklearn/tune_basesearch.py", line 533, in _fit
      self.analysis_ = self._tune_run(X, y, config, resources_per_trial,
    File "/opt/miniforge/lib/python3.9/site-packages/tune_sklearn/tune_search.py", line 808, in _tune_run
      analysis = tune.run(trainable, **run_args)
    File "/opt/miniforge/lib/python3.9/site-packages/ray/tune/tune.py", line 610, in run
      runner.step()
    File "/opt/miniforge/lib/python3.9/site-packages/ray/tune/trial_runner.py", line 709, in step
      self._process_events(timeout=timeout)
    File "/opt/miniforge/lib/python3.9/site-packages/ray/tune/trial_runner.py", line 859, in _process_events
      self._process_trial(trial)
    File "/opt/miniforge/lib/python3.9/site-packages/ray/tune/trial_runner.py", line 886, in _process_trial
      results = self.trial_executor.fetch_result(trial)
    File "/opt/miniforge/lib/python3.9/site-packages/ray/tune/ray_trial_executor.py", line 675, in fetch_result
      result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
    File "/opt/miniforge/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
      return func(*args, **kwargs)
    File "/opt/miniforge/lib/python3.9/site-packages/ray/worker.py", line 1763, in get
      raise value.as_instanceof_cause()
    inostart-model-training-train-1  | ray.exceptions.RayTaskError(LightGBMError): ray::_Inner.train() (pid=138, ip=172.19.0.2, repr=<ray.tune.utils.trainable._Trainable object at 0x7fccd99aebb0>)
    File "/opt/miniforge/lib/python3.9/site-packages/ray/tune/trainable.py", line 319, in train
      result = self.step()
    File "/opt/miniforge/lib/python3.9/site-packages/tune_sklearn/_trainable.py", line 106, in step
      return self._train()
    File "/opt/miniforge/lib/python3.9/site-packages/tune_sklearn/_trainable.py", line 189, in _train
      self._early_stopping_lgbm(i, estimator, X_train, y_train)
    File "/opt/miniforge/lib/python3.9/site-packages/tune_sklearn/_trainable.py", line 128, in _early_stopping_lgbm
      estimator.fit(X_train, y_train, init_model=self.saved_models[i])
    File "/opt/project/src/lgbm_ttr.py", line 9, in fit
      super().fit(X, y, **fit_params)
    File "/opt/miniforge/lib/python3.9/site-packages/sklearn/compose/_target.py", line 246, in fit
      self.regressor_.fit(X, y_trans, **fit_params)
    File "/opt/miniforge/lib/python3.9/site-packages/sklearn/pipeline.py", line 394, in fit
      self._final_estimator.fit(Xt, y, **fit_params_last_step)
    File "/opt/miniforge/lib/python3.9/site-packages/lightgbm/sklearn.py", line 895, in fit
      super().fit(X, y, sample_weight=sample_weight, init_score=init_score,
    File "/opt/miniforge/lib/python3.9/site-packages/lightgbm/sklearn.py", line 748, in fit
      self._Booster = train(
    File "/opt/miniforge/lib/python3.9/site-packages/lightgbm/engine.py", line 292, in train
      booster.update(fobj=fobj)
    File "/opt/miniforge/lib/python3.9/site-packages/lightgbm/basic.py", line 3021, in update
      _safe_call(_LIB.LGBM_BoosterUpdateOneIter(
    File "/opt/miniforge/lib/python3.9/site-packages/lightgbm/basic.py", line 125, in _safe_call
      raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: Out of Resources
```

## Reproducible example
At the moment we do not have a simple code. It is very hard to get as currently it takes 3 hours to get the error.

## Environment info

LightGBM version or commit hash: 3.3.2

Command(s) you used to install LightGBM

We install LightGBM with docker.

```shell
RUN cd /usr/local/src && mkdir lightgbm && cd lightgbm && \
    git clone --recursive --branch stable --depth 1 https://github.com/microsoft/LightGBM && \
    cd LightGBM && mkdir build && cd build && \
    cmake -DUSE_GPU=1 -DOpenCL_LIBRARY=/usr/local/cuda/lib64/libOpenCL.so -DOpenCL_INCLUDE_DIR=/usr/local/cuda/include/ .. && \
    make OPENCL_HEADERS=/usr/local/cuda-8.0/targets/x86_64-linux/include LIBOPENCL=/usr/local/cuda-8.0/targets/x86_64-linux/lib

ENV PATH /usr/local/src/lightgbm/LightGBM:${PATH}

RUN /bin/bash -c "cd /usr/local/src/lightgbm/LightGBM/python-package && python setup.py install --precompile"

```

The code runs with no problems on windows, but it was not dockerized version.
The same issue was reproduced on two different docker host machines: ubuntu and arch linux.

## Additional Comments

The "Out of Resources" on Google returns very few hits. We would appreciate any hints what this phrase could mean, and where its coming from.

**Comment by valentasgruzauskas** [comment]
For ray.TuneSearchCV, we used ASHAScheduler and set bayesian for search_optimization. Lightgbm is also enabled with early stopping. Resources per trial were set to 5 CPU and 0.2 GPU. My guess is that lightgbm cannot find free GPU/CPU, thus we receive the error "Out of Resources". However, not sure how to check if this is the issue.

**Comment by jameslamb** [comment]
Thanks very much for your interest in LightGBM!

> We would appreciate any hints what this phrase could mean, and where its coming from.

You won't find the phrase "Out of Resources" directly in LightGBM's source code.

```shell
git grep -i 'out of resource'
```

However, there are several places where LightGBM catches and re-raises exceptions from the operating system or from other libraries' state. For example, 

https://github.com/microsoft/LightGBM/blob/2871b53e8e5e0ef23590410d7596d91173322ae4/src/cuda/cuda_utils.cpp#L16-L19

https://github.com/microsoft/LightGBM/blob/100a10dafc9648616e007e33a707a1c1cb8a938f/src/network/socket_wrapper.hpp#L168-L175

<hr>

Without a reproducible example, we're not able to provide much more help here other than guesswork. If you're able to reduce this to a reproducible example (ideally one not relying on Ray), it's much more likely that maintainers will devote time to this and help you find a resolution.

If you're not willing or able to provide a reproducible example, doing some of the following might at least give us a bit more information to make better-informed guesses:

* provide the complete Dockerfile used to build your training environment (including `FROM` statement), so we can answer questions like "what python version are you using? what operating system are you on?"
* provide all logs produced, not only the error message
     - that might help us to narrow down where in LightGBM's code this error is being encountered
     - and even better, re-run your LightGBM code with `verbose: 2` in `params` to get DEBUG-level logs
* try to at least reduce your code such that you can encounter this error without `ray`

Otherwise, the maintainers of ray tune are ultimately responsible for the performance of that tool and its integration with frameworks like LightGBM, and you should consider opening an issue at https://github.com/ray-project/ray/issues asking for their help. If you do that, please link to this issue so the two will be connected.
