### ISSUE TITLE
could not parse main worker ipv6 host and port correctly

### ISSUE THREAD

**Issue by 996peasant** [microsoft/LightGBM#5523]
## Description

could not parse main worker host and port correctly。The ipv6 and host is fdbd:dc02:f:172:0:0:0:20:12404
The error log is below.

22/10/05 15:38:50 INFO LightGBMClassifier: sending finished status to driver
22/10/05 15:38:50 INFO LightGBMClassifier: LightGBM worker got nodes for network init: fdbd:dc02:f:172:0:0:0:20:12404
22/10/05 15:38:50 INFO LightGBMClassifier: LightGBM task listening on: 12404
22/10/05 15:38:50 ERROR Executor: Exception in task 0.0 in stage 3.0 (TID 3)
java.lang.Exception: Error: could not parse main worker host and port correctly
	at com.microsoft.azure.synapse.ml.lightgbm.TrainUtils$.getMainWorkerPort(TrainUtils.scala:311)
	at com.microsoft.azure.synapse.ml.lightgbm.TrainUtils$.getReturnBooster(TrainUtils.scala:361)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.trainLightGBM(LightGBMBase.scala:372)
	at com.microsoft.azure.synapse.ml.lightgbm.LightGBMBase.$anonfun$innerTrain$4(LightGBMBase.scala:485)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2(RDDBarrier.scala:51)
	at org.apache.spark.rdd.RDDBarrier.$anonfun$mapPartitions$2$adapted(RDDBarrier.scala:51)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:354)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:318)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:130)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:476)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1516)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:479)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

## Reproducible example

The code that raise error:
    val lgbmodel: LightGBMClassificationModel = lgbclassifier.fit(dftrain)

## Environment info
spark 3.0.1 
with maven dependency:
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>synapseml-lightgbm_2.12</artifactId>
            <version>0.10.1</version>
        </dependency>

LightGBM version or commit hash: synapseml-lightgbm_2.12:0.10.1

Command(s) you used to install LightGBM
spark maven project

**Comment by jameslamb** [comment]
Thanks for using LightGBM!

We do not maintain SynapseML in this project. Please report your issue in that project: https://github.com/microsoft/SynapseML/issues/new/choose.

When you do that, please give them more information than a stack trace and some version numbers. Try to include a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) or at least a more thorough explanation of your setup (e.g. how many executors in your Spark cluster? what values of `params` are you passing to LightGBM?).

If our friends there discover that this is an issue with LightGBM, they'll open a bug report here.

**Comment by 996peasant** [comment]
Think you very much. I will report this issue in [SynapseML](https://github.com/microsoft/SynapseML)

**Comment by jameslamb** [comment]
ok great, thanks! We'll close this for now then.
