### ISSUE TITLE
[python-package] How to custom scikit-learn interface?

### ISSUE THREAD

**Issue by zhenweilin** [microsoft/LightGBM#5684]
Hello LightGBM community! I am currently trying to write a custom classifier with a custom objective function. To do so, I tried to define my own python interface, but when writing the scikit-learn interface, I just modified `LGBMClassifier` to `LGBMClassifier_my`  and the following error occurs:

```bash
[LightGBM] [Fatal] Number of classes must be 1 for non-multiclass training
Traceback (most recent call last):
  File "/nfsshare/home/linzhenwei/ConstraintGBM/LightGBM/example.py", line 19, in <module>
    model.fit(X_train, y_train)
  File "/nfsshare/home/linzhenwei/anaconda3/envs/testxgbnew/lib/python3.10/site-packages/lightgbm/sklearn.py", line 1367, in fit
    self._Booster = train(
  File "/nfsshare/home/linzhenwei/anaconda3/envs/testxgbnew/lib/python3.10/site-packages/lightgbm/engine.py", line 230, in train
    booster = Booster(params=params, train_set=train_set)
  File "/nfsshare/home/linzhenwei/anaconda3/envs/testxgbnew/lib/python3.10/site-packages/lightgbm/basic.py", line 2860, in __init__
    train_set.construct()
  File "/nfsshare/home/linzhenwei/anaconda3/envs/testxgbnew/lib/python3.10/site-packages/lightgbm/basic.py", line 1961, in construct
    self._lazy_init(self.data, label=self.label,
  File "/nfsshare/home/linzhenwei/anaconda3/envs/testxgbnew/lib/python3.10/site-packages/lightgbm/basic.py", line 1606, in _lazy_init
    self.__init_from_np2d(data, params_str, ref_dataset)
  File "/nfsshare/home/linzhenwei/anaconda3/envs/testxgbnew/lib/python3.10/site-packages/lightgbm/basic.py", line 1746, in __init_from_np2d
    _safe_call(_LIB.LGBM_DatasetCreateFromMat(
  File "/nfsshare/home/linzhenwei/anaconda3/envs/testxgbnew/lib/python3.10/site-packages/lightgbm/basic.py", line 175, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError().decode('utf-8'))
lightgbm.basic.LightGBMError: Number of classes must be 1 for non-multiclass training
```

I am very confused, I just changed the name of a class, why did it cause the above error and how should I correct it?

An additional note is that my code does not report an error when the name is `LGBMClassifier`.

```python
from sklearn.datasets import load_iris
import lightgbm as lgb
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split
import numpy as np

# read in the iris data
iris = load_iris()

X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# train
model = lgb.LGBMClassifier_my(max_depth=5, learning_rate=0.1, n_estimators=160, verbosity = 1)
model.fit(X_train, y_train)
print("starting predict:")
# test
ans = model.predict(X_test)

print("ans:", ans)
print("y_test", y_test)
# accuracy
cnt1 = 0
cnt2 = 0
for i in range(len(y_test)):
    if ans[i] == y_test[i]:
        cnt1 += 1
    else:
        cnt2 += 1

print("Accuracy: %.2f %% " % (100 * cnt1 / (cnt1 + cnt2)))

print(lgb.__version__)
print(model.get_params())
```

**Comment by jameslamb** [comment]
Thanks for using LightGBM and for the report!

But the example you've provided is missing some details we need to be able to help you.

* what version of `lightgbm` are you using?
* what version of `scikit-learn`?
* what is `LGBMClassifier_my`? You haven't shown how that's defined.

Trying to run the code you've shared will result in

> AttributeError: module 'lightgbm' has no attribute 'LGBMClassifier_my'

Not the error you've reported.

**Comment by zhenweilin** [comment]
Thank you very much for your answer, I didn't have this problem after I downgraded my LightGBM package version to `3.3.5`.  I was using LightGBM `3.3.5.99` and `1.1.3` scikit-learn version before. The only modification is  changing the name of the class `LGBMClassifier` in the file `python-package/lightgbm/sklearn.py` to `LGBMClassifier_my`, and modify some related code for searching this class.

**Comment by jameslamb** [comment]
If you don't provide the code you used to define `LGBMClassifier_my`, we cannot help you with this report.
