### ISSUE TITLE
Examples Failing on Triton Inference Server

### ISSUE THREAD

**Issue by Andreas237** [microsoft/LightGBM#5968]
## Description
Running all of the examples provided in `./examples/python-guide/` result in segmentation faults.

## Reproducible example
```
cd <path_to_dockerfile>
docker build .
[dockerfile_and_backtrace.zip](https://github.com/microsoft/LightGBM/files/12005842/dockerfile_and_backtrace.zip)

```

## Environment info
Uname -a: Linux 82c5e2d05dc3 5.10.104-tegra #1 SMP PREEMPT Sun Mar 19 07:55:28 PDT 2023 aarch64 aarch64 aarch64 GNU/Linux
Python 3.8.10
Container: [nvcr.io/nvidia/tritonserver:21.10-py3](http://nvcr.io/nvidia/tritonserver:21.10-py3)
Cuda Driver Version: 11.4.2

Host OS: Ubuntu 20.04

LightGBM version or commit hash: v3.3.2

Command(s) you used to install LightGBM

```shell
cd <path_to_dockerfile>
docker build .
```

Test on x86_64 and ARM64 hosts.

## Additional Comments
I ran GDB versus python3, then each example.  The following is the output from each.  Note: each example's final line of code is run before the segfault.

See the text file in the attached zip for the backtrace.
[dockerfile_and_backtrace.zip](https://github.com/microsoft/LightGBM/files/12005839/dockerfile_and_backtrace.zip)

**Comment by jameslamb** [comment]
Sorry for the long delay in response.

@Andreas237 in the future, please provide text files instead of a `.zip` when the data is so small.

I've copied it here.

<details><summary>Dockerfile (click me)</summary>

```dockerfile
FROM nvcr.io/nvidia/tritonserver:21.10-py3

ENV LANG=C.UTF-8 LC_ALL=C.UTF-8

ARG DEBIAN_FRONTEND=noninteractive

RUN rm /usr/local/cuda; ln -s /usr/local/cuda-11.4/ /usr/local/cuda
ENV CUDA_HOME /usr/local/cuda
ENV LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${CUDA_HOME}/lib64
ENV LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:/usr/local/lib
ENV OPENCL_LIBRARIES /usr/local/cuda/lib64
ENV OPENCL_INCLUDE_DIR /usr/local/cuda/include/include
ENV PYTHONPATH /work/src:/work/src/include:..:.

RUN apt-key del 7fa2af80 && \
    update-ca-certificates && \
    echo 'Acquire::https::developer.download.nvidia.com::Verify-Peer "false";' > /etc/apt/apt.conf.d/nvidia-cuda && \
    curl -sS http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/sbsa/3bf863cc.pub | gpg --dearmor | tee /etc/apt/trusted.gpg.d/nvidia_cuda_3bf863cc.gpg

RUN echo "deb [trusted=yes] http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/sbsa /" > /etc/apt/sources.list.d/tensorRT.list && \
    curl -sS  http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu2004/sbsa/7fa2af80.pub | gpg --dearmor | tee /etc/apt/trusted.gpg.d/nvidia_machine-learning_7fa2af80.gpg

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    bzip2 \
    ca-certificates \
    cmake \
    curl \
    gcc \
    g++ \
    gdb \
    git \
    libboost-dev \
    libboost-system-dev \
    libboost-filesystem-dev \
    libbz2-dev \
    libffi-dev \
    libglib2.0-0 \
    libncurses5-dev \
    libssl-dev \
    libsm6 \
    libxext6 \
    libxrender1 \
    make \
    opencl-headers \
    ocl-icd-libopencl1 \
    openssl \
    zlib1g-dev \
    && ldconfig && apt-get clean && apt-get autoclean && apt-get autoremove

# Add OpenCL ICD files for LightGBM
RUN mkdir -p /etc/OpenCL/vendors && \
    echo "libnvidia-opencl.so.1" > /etc/OpenCL/vendors/nvidia.icd

RUN python3 -m pip install --upgrade pip --trusted-host pypi.org && \
    python3 -m pip install \
        connexion[swagger-ui]==2.14.0 \
        filelock \
        flask_cors \
        gast \
        imblearn==0.0 \
        numpy==1.24.3 \
        pandas==1.4.3 \
        protobuf \
        python-socketio[client]==5.7.1 \
        redis==4.3.4 \
        scikit-optimize==0.9.0 \
        scipy==1.10.1 \
        setuptools>=58.2.0 \
        scikit-learn \
        tensorflow-serving-api-gpu==2.12.1 \
        tensorflow_probability==0.17.0 \
        --trusted-host pypi.org

RUN wget --no-check-certificate https://gitlab.com/tenzing/shared-array/-/archive/3.2.2/shared-array-3.2.2.tar && \
    tar -xvf shared-array-3.2.2.tar && \
    cd shared-array-3.2.2 && \
    python3 setup.py build && \
    python3 setup.py install && \
    cd .. && rm -rf shared-array-3.2.2*

RUN cd /usr/local/src && mkdir lightgbm && cd lightgbm && \
    git config --global http.sslverify false && \
    git clone --recursive --branch v3.3.2 --depth 1 https://github.com/microsoft/LightGBM && \
    cd LightGBM && \
    mkdir build && cd build && \
    cmake -DUSE_GPU=1 \
          -DOpenCL_LIBRARY=/usr/lib/aarch64-linux-gnu/libOpenCL.so.1.0.0 \
          -DOpenCL_INCLUDE_DIR=/usr/local/cuda-11.4/targets/sbsa-linux/include/ \
          -DUSE_TIMETAG=ON -DUSE_CUDA=1 -DUSE_DEBUG=1 .. && \
    make -j4 OPENCL_HEADERS=/usr/include/ LIBOPENCL=/usr/lib/aarch64-linux-gnu/libOpenCL.so.1.0.0

ENV PATH /usr/local/src/lightgbm/LightGBM:${PATH}
ENV PYTHONPATH /usr/local/src/lightgbm/LightGBM/python-package:${PYTHONPATH}
RUN python3 -m pip install /usr/local/src/lightgbm/LightGBM/python-package \
    --config-setting="--install-option=--precompile \
    --install-option=--cuda \
    --install-option=--opencl-include-dir=/usr/local/cuda-11.4/targets/sbsa-linux/include/ \
    --install-option=--opencl-library=/usr/lib/aarch64-linux-gnu/libOpenCL.so.1.0.0"

RUN cd /usr/local/src/lightgbm/LightGBM/examples/python-guide && \
    python3 simple_example.py
```

</details>

Logs:

```text
root@82c5e2d05dc3:/usr/local/src/lightgbm/LightGBM/examples/python-guide# gdb -q python3.8

Reading symbols from python3.8...
(No debugging symbols found in python3.8)
(gdb) run simple_example.py

Starting program: /usr/bin/python3.8 simple_example.py

warning: Error disabling address space randomization: Operation not permitted

warning: Probes-based dynamic linker interface failed.

Reverting to original interface.
[Detaching after fork from child process 111]
[Detaching after fork from child process 114]
[Detaching after fork from child process 115]
[Detaching after fork from child process 117]

process 108 is executing new program: /usr/bin/python3.8
[Thread debugging using libthread_db enabled]

Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0xffff935d11e0 (LWP 118)]
[New Thread 0xffff92dd01e0 (LWP 119)]
[New Thread 0xffff905cf1e0 (LWP 120)]
[New Thread 0xffff8ddce1e0 (LWP 121)]
[New Thread 0xffff8b5cd1e0 (LWP 122)]
[New Thread 0xffff88dcc1e0 (LWP 123)]
[New Thread 0xffff865cb1e0 (LWP 124)]
[New Thread 0xffff7d18d1e0 (LWP 125)]
[New Thread 0xffff7c98c1e0 (LWP 126)]
[New Thread 0xffff7a18b1e0 (LWP 127)]
[New Thread 0xffff7598a1e0 (LWP 128)]
[New Thread 0xffff751891e0 (LWP 129)]
[New Thread 0xffff709881e0 (LWP 130)]
[New Thread 0xffff701871e0 (LWP 131)]
[Thread 0xffff701871e0 (LWP 131) exited]
[Thread 0xffff709881e0 (LWP 130) exited]
[Thread 0xffff751891e0 (LWP 129) exited]
[Thread 0xffff7598a1e0 (LWP 128) exited]
[Thread 0xffff7a18b1e0 (LWP 127) exited]
[Thread 0xffff7c98c1e0 (LWP 126) exited]
[Thread 0xffff7d18d1e0 (LWP 125) exited]
[Thread 0xffff92dd01e0 (LWP 119) exited]
[Thread 0xffff88dcc1e0 (LWP 123) exited]
[Thread 0xffff8b5cd1e0 (LWP 122) exited]
[Thread 0xffff905cf1e0 (LWP 120) exited]
[Thread 0xffff935d11e0 (LWP 118) exited]
[Thread 0xffff8ddce1e0 (LWP 121) exited]
[Thread 0xffff865cb1e0 (LWP 124) exited]
[Detaching after fork from child process 132]
[New Thread 0xffff865cb1e0 (LWP 133)]
[New Thread 0xffff88dcc1e0 (LWP 134)]
[New Thread 0xffff8b5cd1e0 (LWP 135)]
[New Thread 0xffff8ddce1e0 (LWP 136)]
[New Thread 0xffff754d71e0 (LWP 137)]
[New Thread 0xffff6ae261e0 (LWP 138)]
[New Thread 0xffff6a6251e0 (LWP 139)]

Loading data...

Starting training...
/usr/local/src/lightgbm/LightGBM/python-package/lightgbm/engine.py:181: UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
  _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "
[LightGBM] [Warning] Auto-choosing col-wise multi-threading, the overhead of testing was 0.015436 seconds.

You can set `force_col_wise=true` to remove the overhead.
[1]     valid_0's l2: 0.244076  valid_0's l1: 0.493018

Training until validation scores don't improve for 5 rounds
[2]     valid_0's l2: 0.240297  valid_0's l1: 0.489056
[3]     valid_0's l2: 0.235733  valid_0's l1: 0.484089
[4]     valid_0's l2: 0.231352  valid_0's l1: 0.479088
[5]     valid_0's l2: 0.228939  valid_0's l1: 0.476159
[6]     valid_0's l2: 0.22593   valid_0's l1: 0.472664
[7]     valid_0's l2: 0.222515  valid_0's l1: 0.468425
[8]     valid_0's l2: 0.219569  valid_0's l1: 0.464594
[9]     valid_0's l2: 0.2168    valid_0's l1: 0.460795
[10]    valid_0's l2: 0.214371  valid_0's l1: 0.457276
[11]    valid_0's l2: 0.211988  valid_0's l1: 0.453923
[12]    valid_0's l2: 0.210264  valid_0's l1: 0.451235
[13]    valid_0's l2: 0.208926  valid_0's l1: 0.448992
[14]    valid_0's l2: 0.207403  valid_0's l1: 0.44634
[15]    valid_0's l2: 0.20601   valid_0's l1: 0.444016
[16]    valid_0's l2: 0.204447  valid_0's l1: 0.441362
[17]    valid_0's l2: 0.202712  valid_0's l1: 0.43891
[18]    valid_0's l2: 0.201066  valid_0's l1: 0.436192
[19]    valid_0's l2: 0.1998    valid_0's l1: 0.433884
[20]    valid_0's l2: 0.198063  valid_0's l1: 0.431129

Did not meet early stopping. Best iteration is:
[20]    valid_0's l2: 0.198063  valid_0's l1: 0.431129

Saving model...

Starting predicting...

The RMSE of prediction is: 0.4450426449744025
--Type <RET> for more, q to quit, c to continue without paging--c
 
Thread 1 "python3.8" received signal SIGSEGV, Segmentation fault.

0x0000ffff95687e2c in sem_wait@@GLIBC_2.17 () from /lib/aarch64-linux-gnu/libpthread.so.0
(gdb) bt
#0  0x0000ffff95687e2c in sem_wait@@GLIBC_2.17 () from /lib/aarch64-linux-gnu/libpthread.so.0
#1  0x00000000004d2234 in PyThread_acquire_lock ()
#2  0x000000000064cdc0 in ?? ()
#3  0x000000000064ce7c in PyGILState_Ensure ()
#4  0x0000ffff81b1b250 in ?? () from /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-aarch64-linux-gnu.so
#5  0x0000ffff81afcdac in ?? () from /lib/aarch64-linux-gnu/libffi.so.7
#6  0x0000ffff81afd174 in ?? () from /lib/aarch64-linux-gnu/libffi.so.7
#7  0x0000ffff7027c2b4 in LightGBM::Log::Write (level=LightGBM::LogLevel::Info, level_str=0xffff70699e38 "Info",
    format=0xffff7069f8c0 "%s costs:\t %f", val=...)
    at /usr/local/src/lightgbm/LightGBM/include/LightGBM/utils/log.h:149
#8  0x0000ffff7027af14 in LightGBM::Log::Info (format=0xffff7069f8c0 "%s costs:\t %f")
    at /usr/local/src/lightgbm/LightGBM/include/LightGBM/utils/log.h:101
#9  0x0000ffff702a225c in LightGBM::Common::Timer::Print (this=0xffff70986458 <LightGBM::global_timer>)
    at /usr/local/src/lightgbm/LightGBM/include/LightGBM/utils/common.h:1002
#10 0x0000ffff702a1fa0 in LightGBM::Common::Timer::~Timer (this=0xffff70986458 <LightGBM::global_timer>,
    __in_chrg=<optimized out>) at /usr/local/src/lightgbm/LightGBM/include/LightGBM/utils/common.h:963
#11 0x0000ffff956df84c in ?? () from /lib/aarch64-linux-gnu/libc.so.6
#12 0x0000ffff956df9dc in exit () from /lib/aarch64-linux-gnu/libc.so.6
#13 0x0000ffff956ca094 in __libc_start_main () from /lib/aarch64-linux-gnu/libc.so.6
#14 0x0000000000599468 in _start ()

Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

I'm unsure, but looks to me like maybe that segfault is happening inside the `Timer` code from LightGBM. Could you try compiling again with `-DUSE_TIMETAG=OFF` and let us know if that fixes it?
