### ISSUE TITLE
[regression in 4.0.0] Python binding build fails: pyproject_metadata.ConfigurationError: License file not found (`LICENSE`) and cmake issues

### ISSUE THREAD

**Issue by yurivict** [microsoft/LightGBM#5977]
## Description
Complete log:
```
cd /usr/ports/misc/py-lightgbm/work-py39/LightGBM-4.0.0/python-package && /usr/bin/env XDG_DATA_HOME=/usr/ports/misc/py-lightgbm/work-py39  XDG_CONFIG_HOME=/usr/ports/misc/py-lightgbm/work-py39  XDG_CACHE_HOME=/usr/ports/misc/py-lightgbm/work-py39/.cache  HOME=/usr/ports/misc/py-lightgbm/work-py39 PATH=/usr/local/libexec/ccache:/usr/ports/misc/py-lightgbm/work-py39/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin PKG_CONFIG_LIBDIR=/usr/ports/misc/py-lightgbm/work-py39/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS=""  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -I/usr/local/include/eigen3 "  MANPREFIX="/usr/local" CCACHE_DIR="/tmp/.ccache" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" /usr/local/bin/python3.9 -m build --no-isolation --wheel 
* Getting build dependencies for wheel...
* Building wheel...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/local/lib/python3.9/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/usr/local/lib/python3.9/site-packages/scikit_build_core/build/__init__.py", line 32, in build_wheel
    return _build_wheel_impl(
  File "/usr/local/lib/python3.9/site-packages/scikit_build_core/build/wheel.py", line 86, in _build_wheel_impl
    metadata = get_standard_metadata(pyproject, settings)
  File "/usr/local/lib/python3.9/site-packages/scikit_build_core/settings/metadata.py", line 47, in get_standard_metadata
    return StandardMetadata.from_pyproject(pyproject_dict)
  File "/usr/local/lib/python3.9/site-packages/pyproject_metadata/__init__.py", line 233, in from_pyproject
    cls._get_license(fetcher, project_dir),
  File "/usr/local/lib/python3.9/site-packages/pyproject_metadata/__init__.py", line 364, in _get_license
    raise ConfigurationError(
pyproject_metadata.ConfigurationError: License file not found (`LICENSE`)

ERROR Backend subprocess exited when trying to invoke build_wheel
```

## Environment info

LightGBM version or commit hash: 4.0.0
Python-3.9
FreeBSD 13.2

**Comment by yurivict** [comment]
The build is done in the ```python-package``` sub-folder. The lightgbm's C++ library is already installed.  Then build should be self-sufficient and it should build just the Python binding.

Once the LICENSE file path is fixed - it fails to find CMakeLists.txt which doesn't exist in ```python-package```:
```
cd /usr/ports/misc/py-lightgbm/work-py39/LightGBM-4.0.0/python-package && /usr/bin/env XDG_DATA_HOME=/usr/ports/misc/py-lightgbm/work-py39  XDG_CONFIG_HOME=/usr/ports/misc/py-lightgbm/work-py39  XDG_CACHE_HOME=/usr/ports/misc/py-lightgbm/work-py39/.cache  HOME=/usr/ports/misc/py-lightgbm/work-py39 PATH=/usr/local/libexec/ccache:/usr/ports/misc/py-lightgbm/work-py39/.bin:/home/yuri/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin PKG_CONFIG_LIBDIR=/usr/ports/misc/py-lightgbm/work-py39/.pkgconfig:/usr/local/libdata/pkgconfig:/usr/local/share/pkgconfig:/usr/libdata/pkgconfig MK_DEBUG_FILES=no MK_KERNEL_SYMBOLS=no SHELL=/bin/sh NO_LINT=YES PREFIX=/usr/local  LOCALBASE=/usr/local  CC="cc" CFLAGS="-O2 -pipe  -fstack-protector-strong -fno-strict-aliasing "  CPP="cpp" CPPFLAGS=""  LDFLAGS=" -fstack-protector-strong " LIBS=""  CXX="c++" CXXFLAGS="-O2 -pipe -fstack-protector-strong -fno-strict-aliasing  -I/usr/local/include/eigen3 "  MANPREFIX="/usr/local" CCACHE_DIR="/tmp/.ccache" BSD_INSTALL_PROGRAM="install  -s -m 555"  BSD_INSTALL_LIB="install  -s -m 0644"  BSD_INSTALL_SCRIPT="install  -m 555"  BSD_INSTALL_DATA="install  -m 0644"  BSD_INSTALL_MAN="install  -m 444" /usr/local/bin/python3.9 -m build --no-isolation --wheel 
* Getting build dependencies for wheel...
* Building wheel...
2023-07-14 09:43:11,088 - scikit_build_core - INFO - CMake version: 3.26.1
*** scikit-build-core 0.4.7 using CMake 3.26.1 (wheel)
2023-07-14 09:43:11,092 - scikit_build_core - INFO - Build directory: /tmp/tmp1jfabfh9/build
2023-07-14 09:43:11,093 - scikit_build_core - WARNING - No license files found, set wheel.license-files to [] to suppress this warning
*** Configuring CMake...
2023-07-14 09:43:11,300 - scikit_build_core - INFO - Ninja version: 1.11.1
loading initial cache file /tmp/tmp1jfabfh9/build/CMakeInit.txt
CMake Error: The source directory "/usr/ports/misc/py-lightgbm/work-py39/LightGBM-4.0.0/python-package" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

The previous version 3.3.5 was building fine using setup.py and distutils. Now you removed setup.py, and pyproject.toml fails to build the Python binding separately, which is a regression.

**Comment by jameslamb** [comment]
This pattern you're using is no longer supporting as of LightGBM v4.0.0.

```shell
cd python-package
python -m build --no-isolation --wheel
```

Instead, building a wheel from sources here in source control requires running a shell script, as described in -m build --no-isolation --wheel.

```shell
sh build-python.sh bdist_wheel
```

**Comment by yurivict** [comment]
This works, thanks.
