### ISSUE TITLE
[ci] AppVeyor Python CI jobs failing: "module 'numpy' has no attribute 'typeDict' Command"

### ISSUE THREAD

**Issue by jameslamb** [microsoft/LightGBM#5995]
## Description

python-package CI jobs on Windows in this project have been failing for the last day with the following error

> Traceback (most recent call last):
  File "C:\projects\lightgbm\examples\python-guide\dataset_from_multi_hdf5.py", line 5, in <module>
    import h5py
  File "C:\Miniconda3-x64\envs\test-env\lib\site-packages\h5py\__init__.py", line 46, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py\_conv.pyx", line 1, in init h5py._conv
  File "h5py\h5t.pyx", line 293, in init h5py.h5t
  File "C:\Users\appveyor\AppData\Roaming\Python\Python38\site-packages\numpy\__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'typeDict'

## Reproducible example

* AppVeyor, MSVC, Python 3.8 ([build link](https://ci.appveyor.com/project/guolinke/lightgbm/builds/47597443/job/5qmuo2u90djnlyfi))
* AppVeyor, MINGW, Python 3.8 ([build link](https://ci.appveyor.com/project/guolinke/lightgbm/builds/47597443/job/ie6j5sbd0wn3lgan))

This isn't happening on any of the Windows python-package CI jobs on Azure DevOps ([link](https://dev.azure.com/lightgbm-ci/lightgbm-ci/_build/results?buildId=14951&view=results)).

The issue is happening in this block of tests (only run on AppVeyor + the one Azure Devops `TASK=regular` job), where a few more dependencies are installed to run the examples in the `examples/` directory.

https://github.com/microsoft/LightGBM/blob/8b1ab4f0ad554fa6edb5144a3a913faf140701aa/.ci/test_windows.ps1#L123-L135

## Environment info

LightGBM version or commit hash: latest `master` (https://github.com/microsoft/LightGBM/commit/8b1ab4f0ad554fa6edb5144a3a913faf140701aa), and all active PRs

## Additional Comments

As described in https://stackoverflow.com/a/74969328/3986677 ...

> `np.typeDict` is a deprecated alias for `np.sctypeDict` and has been so for over 14 years

It was removed around `numpy` 1.21, in 2020 (see https://github.com/numpy/numpy/pull/17586).

**Comment by jameslamb** [comment]
Looks like in those jobs, we're getting `h5py==2.10.0`

```text
h5py-2.10.0                |nompi_py38he6c2248_106         934 KB  conda-forge
```

That release is from September 2019 (https://pypi.org/project/h5py/2.10.0/).

So maybe the issue is some `conda-forge` metadata or something? I'll try putting a floor on `h5py` to see if we can force the use of a newer version.
