### ISSUE TITLE
Python only single feature number of used features: 0 [LightGBM] [Info] No further splits with positive gain, best gain: -infTrained a tree with leaves=1 and max_depth=1

### ISSUE THREAD

**Issue by lai-bluejay** [Microsoft/LightGBM#622]
i want to use gbdt to bin my single feature. one of the feature has exception.
light gbm told me that  

```shell
[LightGBM] [Info] Number of positive: 24149, number of negative: 106400
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data: 130549, number of used features: 0
[LightGBM] [Info] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Trained a tree with leaves=1 and max_depth=1
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split 
```

the feature vector shape:(130549, 1), max  8.0,  min  1.0
other params are 
```python
        num_leaves = 9
        ins_len = len(feature)
        min_data_in_leaf = int(ins_len / num_leaves / 3)
        # TODO  min_sum_hessian_in_leaf
        bt = "gbdt"
        lgb_params = {
            'learning_rate': 1.0,
            'booster': bt,
            'objective': 'binary',
            'eval_metric': ['auc', 'logloss'],
            'nthread': 12,
            'num_trees': 1,
            'min_data_in_leaf': min_data_in_leaf,
            'tree_method': 'hist',
            'num_leaves': num_leaves,
            'max_bins': 1024,
        }
```

is there other important params that i didn't set wright?
or where can i check the histogram method? Because lightgbm only have total 0 bins.

## Environment info
Operating System: linux
CPU: Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz  cores  16
C++/Python/R version: python 2.7.13

## Error Message:
```shell
[LightGBM] [Info] Number of positive: 24149, number of negative: 106400
[LightGBM] [Info] Total Bins 0
[LightGBM] [Info] Number of data: 130549, number of used features: 0
[LightGBM] [Info] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Trained a tree with leaves=1 and max_depth=1
[LightGBM] [Warning] Stopped training because there are no more leaves that meet the split requirements.
[{u'num_leaves': 2, u'tree_index': 0, u'tree_structure': {u'internal_count': 130549, u'right_child': {u'leaf_value': 0.18498035220491924, u'leaf_index': 1, u'leaf_parent': 0, u'leaf_count': 130549}, u'split_feature': 0, u'internal_value': 0, u'threshold': 0, u'split_gain': 1, u'split_index': 0, u'decision_type': u'no_greater', u'left_child': {u'leaf_value': 0.18498035220491924, u'leaf_index': 0, u'leaf_parent': 0, u'leaf_count': 0}}, u'shrinkage': 1}]
Traceback (most recent call last):
  File "monthly_iteration_conan.py", line 199, in <module>
    feature_vali=False)
  File "monthly_iteration_conan.py", line 117, in train_model
    iter_pipline.build()
  File "/data/home/laihongchang/projects/conan/app/../conan/engine/base.py", line 271, in build
    ins.build()
  File "/data/home/laihongchang/projects/conan/app/../conan/layers/auto_binning.py", line 829, in build
    (delete_list,bins_model_save) = self.single_autobinning(featuresmatrix,labelvector,featurename)
  File "/data/home/laihongchang/projects/conan/app/../conan/layers/auto_binning.py", line 684, in single_autobinning
    result_bins_box = auto_binning.binning()
  File "/data/home/laihongchang/projects/conan/app/../conan/layers/auto_binning.py", line 526, in binning
    init_bins_box = self.mapping_func()
  File "/data/home/laihongchang/projects/conan/app/../conan/layers/auto_binning.py", line 446, in mapping_func
    init_map = self.discrete_method_map[self.discrete_method_name](feature_value_list)
  File "/data/home/laihongchang/projects/conan/app/../conan/layers/auto_binning.py", line 334, in discrete_method_lgbm_dt
    tree_structure = tree_info[1]['tree_structure']
IndexError: list index out of range
```
## Steps to reproduce

1.
2.
3.

**Comment by guolinke** [comment]
@lai-bluejay 
try to use "min_data_in_leaf =1" ? 
And can you provide the ```distinct_value``` and its ```occurred count``` of that single feature?

**Comment by guolinke** [comment]
@lai-bluejay any updates ?
