### ISSUE TITLE
[dask] Throw error "bytes object is too large" when train large dataset for lightgbm on high performance single host

### ISSUE THREAD

**Issue by flybywind** [microsoft/LightGBM#6228]
Hi, team, Recently we are trying to train a lightgbm model on a dataset of about 100GiB on a high performance machine with 100cores and 400G RAM.
I used a local cluster and run the code referring this [example](https://github.com/microsoft/LightGBM/blob/master/examples/python-guide/dask/binary-classification.py)
The version for lightgbm and dask is
dask 2023.5.0
lightgbm 3.3.5

And I got the the error like as below: Any suggestion ? Thank u very much

```
/usr/local/lib/python3.8/site-packages/lightgbm/dask.py:526: UserWarning: Parameter n_jobs will be ignored.
  _log_warning(f"Parameter {param_alias} will be ignored.")
/usr/local/lib/python3.8/site-packages/lightgbm/dask.py:526: UserWarning: Parameter nthread will be ignored.
  _log_warning(f"Parameter {param_alias} will be ignored.")
/usr/local/lib/python3.8/site-packages/distributed/client.py:3108: UserWarning: Sending large graph of size 76.51 GiB.
This may cause some slowdown.
Consider scattering data ahead of time and using futures.
  warnings.warn(
2023-12-07 23:19:08,103 - distributed.protocol.core - CRITICAL - Failed to Serialize
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/distributed/protocol/core.py", line 109, in dumps
    frames[0] = msgpack.dumps(msg, default=_encode_default, use_bin_type=True)
  File "/usr/local/lib/python3.8/site-packages/msgpack/__init__.py", line 36, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 231, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 264, in msgpack._cmsgpack.Packer._pack
  File "msgpack/_packer.pyx", line 202, in msgpack._cmsgpack.Packer._pack
ValueError: bytes object is too large
2023-12-07 23:19:08,107 - distributed.comm.utils - ERROR - bytes object is too large
```

**Comment by jmoralez** [comment]
Hey @flybywind, thanks for using LightGBM. Is there a reason why you're using the dask interface on a single machine? If you have one big machine you'd get better and faster results using the local interface. Also if you can provide at least the code you're running it'd help, we can't really tell what's happening just based on those logs.

**Comment by flybywind** [comment]
thanks @jmoralez the reason I used it in local host is to run some test and then extend to a remote cluster. 
by using the local interface, do u mean the pandas api ? 
My code is just the copy of the example link I post before, just the dataset changed.

**Comment by flybywind** [comment]
got it @jmoralez !
I will make more shots and see
