### ISSUE TITLE
Version 3.3.5 to Version 4.3.0

### ISSUE THREAD

**Issue by boneatjp** [microsoft/LightGBM#6309]
## Description
Having

System.AccessViolationException
  HResult=0x80004003
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=<例外のソースを評価できません>
  スタック トレース:
<例外のスタック トレースを評価できません>

## Reproducible example
Installing Version 4.3.0

## Environment info
Using :
Microsoft.ML Version 3.0.1
Microsoft.ML.AutoML Version 0.21.1
Microsoft.ML.CpuMath Version 3.0.1
Microsoft.ML.DataView Version 3.0.1
Microsoft.ML.FastTree Version 3.0.1
Microsoft.ML.LightGbm Version 3.0.1
Microsoft.ML.Mkl.Compreonents Version 3.0.1
Microsoft.ML.Mkl.Redist Version 3.0.1

Under OS Version: 
Windows 11 Pro Version 23H2
OS Build 22631.3007

LightGBM version or commit hash:
Without Installing LightGBM Version 4.3.0, it should be Version 3.3.5

Command(s) you used to install LightGBM
After installing LightGBM Version 4.3.0,

```shell
Having problem 'System.AccessViolationException' in Microsoft.ML.LightGbm.dll
```

Am I suppose to not use it in this case?

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

> *Without Installing LightGBM Version 4.3.0, it should be Version 3.3.5*

I don't understand this statement, could you please elaborate or explain it a different way?

Beyond that, can you tell us more about how you're using LightGBM? For example, are you able to provide a minimal code sample that results in the same error?

**Comment by boneatjp** [comment]
I'm using the packages with NuGet in Visual Studio Community 2022 mentioned for my app, if I try to use LightGBM with version 4.0.0 or later on NuGet in VS Comuunity 2022, I'm having the error I mentioned.  If I don't install LightGBM Version 4.0.0 or later on NuGet, my app works fine.  If I install LightGBM Version 4.0.0 or later on NuGet, my app ends up with the error.

So, I thought there might have been change between version 3.3.5 and version 4.0.0 or later.  If you need minimal code sample, I'll try to write it this weekend.

**Comment by jameslamb** [comment]
> *If I install LightGBM Version 4.0.0 or later on NuGet, my app ends up with the error.*

Yes, LightGBM 4.0.0 contains 2+ years of changes relative to v3.3.5. Without more information, we won't be able to help.

**Comment by boneatjp** [comment]
[AutoMLSample.zip](https://github.com/microsoft/LightGBM/files/14312284/AutoMLSample.zip)

This is the small sample project which gets the error I mentioned.  If you uninstall LightGBM Version 4.3.0 using NuGet Package Manager, it should end without getting any error.

Can you help about this error I'm having?

**Comment by boneatjp** [comment]
I'm not sure if I gave enough information to check the problem.

**Comment by jameslamb** [comment]
> I'm not sure if I gave enough information to check the problem.

I don't know, sorry. It does look more likely to help someone find the root cause than your original post.

But I personally have never compiled or run a `C#` program and don't have easy access to a Windows development environment. I'll try to help with this when I can, otherwise hopefully someone else will be able to help you.

---

I've also changed the title of this issue to make it more specific, please do modify it if I've misunderstood and misstated the problem.

**Comment by winest** [comment]
I can help to provide a sample code to reproduce the issue

```c#
using Microsoft.ML;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.LightGbm;

namespace LambdaRankExample
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create MLContext
            var mlContext = new MLContext();

            // Define training data
            var trainData = new List<RankingData>
            {
                // First query results
                new RankingData { Features = new float[] { 1.0f, 0.1f, 0.2f }, Label = 4, GroupId = 0 },
                new RankingData { Features = new float[] { 0.7f, 0.4f, 0.5f }, Label = 3, GroupId = 0 },
                new RankingData { Features = new float[] { 0.6f, 0.8f, 0.9f }, Label = 1, GroupId = 0 },
                // Second query results
                new RankingData { Features = new float[] { 0.8f, 0.2f, 0.3f }, Label = 3, GroupId = 1 },
                new RankingData { Features = new float[] { 0.5f, 0.6f, 0.7f }, Label = 2, GroupId = 1 },
                new RankingData { Features = new float[] { 0.3f, 0.4f, 0.5f }, Label = 1, GroupId = 1 },
                new RankingData { Features = new float[] { 0.2f, 0.1f, 0.4f }, Label = 1, GroupId = 1 },
                new RankingData { Features = new float[] { 0.9f, 0.7f, 0.6f }, Label = 0, GroupId = 1 }
            };

            // Load training data
            var trainDataView = mlContext.Data.LoadFromEnumerable(trainData);

            // Define LightGBM ranking trainer options
            var options = new LightGbmRankingTrainer.Options
            {
                LabelColumnName = nameof(RankingData.Label),
                FeatureColumnName = nameof(RankingData.Features),
                RowGroupColumnName = nameof(RankingData.GroupId),
                NumberOfLeaves = 7,
                LearningRate = 0.1,
                NumberOfIterations = 100,
                //MinimumExampleCountPerGroup = 1,
                //MinimumExampleCountPerLeaf = 20,
                //MaximumBinCountPerFeature = 1000
            };

            // Define the training pipeline
            var pipeline = mlContext.Ranking.Trainers.LightGbm(options);

            // Train the model
            var model = pipeline.Fit(trainDataView);

            // Define test data
            var testData = new List<RankingData>
            {
                new RankingData { Features = new float[] { 0.8f, 0.2f, 0.3f } },
                new RankingData { Features = new float[] { 0.5f, 0.6f, 0.7f } }
            };

            // Load test data
            var testDataView = mlContext.Data.LoadFromEnumerable(testData);

            // Perform predictions
            var predictions = model.Transform(testDataView);

            // Extract scores
            var scores = mlContext.Data.CreateEnumerable<RankingPrediction>(predictions, reuseRowObject: false);

            // Output predictions
            foreach (var score in scores)
            {
                Console.WriteLine($"Prediction: {score.Score}");
            }
        }
    }

    public class RankingData
    {
        [VectorType(3)]
        public float[] Features { get; set; }
        public float Label { get; set; }
        public uint GroupId { get; set; }
    }

    public class RankingPrediction
    {
        public float Score { get; set; }
    }
}
``` 

Which will return at runtime
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Microsoft.ML.Trainers.LightGbm.WrappedLightGbmInterface.DatasetSetField(SafeDataSetHandle, System.String, IntPtr, Int32, CApiDType)
--------------------------------
   at Microsoft.ML.Trainers.LightGbm.Dataset.SetLabel(Single[])
   at Microsoft.ML.Trainers.LightGbm.Dataset..ctor
```

I am using Visual Studio 2022 Enterprise 64bit version 17.12.3

microsoft.ml\4.0.0\
lightgbm\4.5.0\
microsoft.ml.onnxruntime\1.20.1\
microsoft.ml.lightgbm\4.0.0\
microsoft.ml.tokenizers\1.0.0\
microsoft.ml.onnxtransformer\4.0.0\

**Comment by BFuerchau** [comment]
I have updated my C#-project which is running AutoML since years.
With Version lightgbm 4.5.0 i get also the accessviolationexception.
The tip to downgrade to 3.3.5 solve the problem also for me.

I hope, that in the Future the solution will be found.

**Comment by ericdransfeldt** [comment]
Mine is crashing with the same error in lightgbm 4.6.. Here's the stack:

at Microsoft.ML.Trainers.LightGbm.WrappedLightGbmInterface.DatasetSetField(SafeDataSetHandle handle, String field, IntPtr array, Int32 len, CApiDType type)
   at Microsoft.ML.Trainers.LightGbm.Dataset.SetLabel(Single[] labels)
   at Microsoft.ML.Trainers.LightGbm.Dataset..ctor(Double[][] sampleValuePerColumn, Int32[][] sampleIndicesPerColumn, Int32 numCol, Int32[] sampleNonZeroCntPerColumn, Int32 numSampleRow, Int32 numTotalRow, String param, Single[] labels, Single[] weights, Int32[] groups)
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.CreateDatasetFromSamplingData(IChannel ch, Factory factory, Int32 numRow, String param, Single[] labels, Single[] weights, Int32[] groups, CategoricalMetaData catMetaData, Dataset& dataset)
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.LoadTrainingData(IChannel ch, RoleMappedData trainData, CategoricalMetaData& catMetaData)
   at Microsoft.ML.Trainers.LightGbm.LightGbmTrainerBase`4.TrainModelCore(TrainContext context)
   at Microsoft.ML.Trainers.TrainerEstimatorBase`2.TrainTransformer(IDataView trainSet, IDataView validationSet, IPredictor initPredictor)
   at Microsoft.ML.Data.EstimatorChain`1.Fit(IDataView input)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.Run(TrialSettings settings)
   at Microsoft.ML.AutoML.SweepablePipelineRunner.RunAsync(TrialSettings settings, CancellationToken ct)
   at Microsoft.ML.AutoML.AutoMLExperiment.<RunAsync>d__24.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.ML.AutoML.AutoMLExperiment.RunAsync(CancellationToken ct)
   at Microsoft.ML.AutoML.AutoMLExperiment.Run()
