### ISSUE TITLE
Windows 7 runtime error

### ISSUE THREAD

**Issue by ruisnowy** [microsoft/LightGBM#6477]
python 3.7.16
lightgbn 4.3.0
pyinstaller 5.1

After being packaged into exe, it runs normally on Win10 and reports an error on Win7sp1
The error message is as follows：
Traceback (most recent call last):
  File "PyInstaller\loader\pyimod04_ctypes.py", line 53, in __init__
  File "ctypes\__init__.py", line 364, in __init__
OSError: [WinError 126] 找不到指定的模块。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "recommend\pay_app.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "recommend\predict_service.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "recommend\allocation_pre.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "lightgbm\__init__.py", line 8, in <module>
    from .basic import Booster, Dataset, Sequence, register_logger
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "lightgbm\basic.py", line 247, in <module>
    _LIB = _load_lib()
  File "lightgbm\basic.py", line 232, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "ctypes\__init__.py", line 442, in LoadLibrary
  File "PyInstaller\loader\pyimod04_ctypes.py", line 55, in __init__
pyimod04_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\czj_by9\\AppData\\Local\\Temp\\_MEI43402\\lightgbm\\bin\\lib_lightgbm.dll'. Most likely this dynlib/dll was not found when the application was frozen

**Comment by jameslamb** [comment]
Thanks for using LightGBM.

Windows 7 reached end-of-life several years ago: https://support.microsoft.com/en-us/windows/windows-7-support-ended-on-january-14-2020-b75d4580-2cc7-895a-2c9c-1466d9a53962

LightGBM does not support it.

If you can provide details like the specific commands you used to install it, we can try to help a little (in case there are simple changes that could fix this for you), but otherwise you will have to use at least Windows 10 to use newer versions of LightGBM.

**Comment by ruisnowy** [comment]
@jameslamb  thanks
All versions of LightGBM do not support Windows 7? Can the lower version be supported?

**Comment by jameslamb** [comment]
You can try an older version like v3.3.5 but it will be difficult for us to help much if you don't share the commands you're using, reason you need to use pyinstaller, reason you need Python 3.7 (also end-of-life), and exact code you're running.
