### ISSUE TITLE
AttributeError: module 'lightgbm' has no attribute 'Dataset'

### ISSUE THREAD

**Issue by yuan76316** [Microsoft/LightGBM#766]
Please search your question on previous issues, [stackoverflow](https://stackoverflow.com/questions/tagged/lightgbm) or other search engines before you open a new one.

For bugs and unexpected issues, please provide following information, so that we could reproduce on our system.

## Environment info
Operating System: ubuntu 16.04
CPU:  
C++/Python/R version: 3.6

## Error Message:
Traceback (most recent call last):
  File "lightgbm3.py", line 6, in <module>
    import lightgbm as lgb
  File "/root/instacart/code/lightgbm.py", line 147, in <module>
AttributeError: module 'lightgbm' has no attribute 'Dataset'

## Reproducible examples
```
import pandas as pd
import numpy as np
import datetime
begin = datetime.datetime.now()
from pymongo import MongoClient
import lightgbm as lgb



Word2Vec = pd.read_csv("../input/newFeaturesWord2Vec.csv")
data = pd.read_csv("../input/generalisedData0729.csv")
Markov_chain = pd.read_csv("../input/Markov_chain.csv")
newFeaturesWord2vec_users = pd.read_csv("../input/newFeaturesWord2vec_users.csv")
# annoyResult = pd.read_csv("../input/annoyResult.csv")
order_streaks = pd.read_csv("../input/order_streaks.csv")
cluster = pd.read_csv("../input/cluster.csv")
del cluster["Unnamed: 0"]
data = pd.merge(data,Word2Vec,how='left', on=["product_id"])
Word2Vec = None
data = pd.merge(data,order_streaks,how='left', on=["user_id","product_id"])
order_streaks = None
data = pd.merge(data,Markov_chain,how='left', on=["product_id"])
Markov_chain = None
data = pd.merge(data,newFeaturesWord2vec_users,how='left', on=["product_id"])
newFeaturesWord2vec_users = None
data = pd.merge(data,cluster,how='left', on=["user_id"])
cluster = None


data = data[data.product_id!= 0]


# del data["Unnamed: 0_y"]
# del data["user_orders"]
# del data["prod_reorder_ratio"]
del data['Unnamed: 0_y']
del data['prod_reorder_ratio']
del data['user_orders']
# del data["aisle_preferred_day"]


print (list(data.columns))
# del data["Unnamed: 0"]
# del data["order_frequency"]
# del data["user_median_day"]
# del data["up_min_cart_position"]


train = data.loc[data['eval_set'] == "train"]
del train["eval_set"]
# del train["user_id"]
train["product_id"]
train["order_id"]
train["reordered"] = train["reordered"].fillna(value=0)
reordered = train['reordered']
# reordered.to_csv('../input/reordered.csv', index=False)
del train["reordered"]

test = data[data['eval_set'] == "test"]
del test["eval_set"]
test["user_id"]
del test["reordered"]
data = None


train = train.replace([np.inf, -np.inf], np.nan)
test = test.replace([np.inf, -np.inf], np.nan)
train = train.fillna(train.mean())
test = test.fillna(test.mean())
# train = singleFeatureSacle(train)
# test = singleFeatureSacle(test)

newFeatures =None

client = MongoClient('mongodb://localhost:27000/')
db = client.instacart_database
collection = db['gridSearchResult']

# print (train.shape)
# print (test.shape)
print (reordered.shape)
print (train.shape)
print (test.shape)
print ("-----------------------------")

params = {'objective': 'binary',
                  'metric': 'binary_logloss',
                  'max_depth': 6,
                  'min_child_weight': 10,
                  # 'learning_rate' : 0.1,
                  # 'num_leaves' : 255,
                  # 'num_trees' : 500,
                  # 'num_threads' : 16,
                  # 'min_data_in_leaf' : 0,
                  # 'min_sum_hessian_in_leaf' : 100
                  'lambda_l2': 10,
                  'lambda_l1': 2e-05,
                   'nthread': 31,
                  }

# param = {
#         "objective" : ["reg:logistic"],
#         "eval_metric" : ["logloss"],
#         "eta" : [0.1],
#         "max_depth" : [6],
#         "min_child_weight" : [10],
#         "gamma" : [0.7],
#         "subsample" : [0.76],
#         "colsample_bytree" : [0.95],
#         "alpha" : [2e-05],
#         "lambda" : [100]
#     }
# getALLPossible(cv_params)

mayDeletedList =  [
 ['user_total_products', 106],
 ['8_y', 106],
 ['4_y', 105],
 ['3_y', 104],
 ['up_median_cart_position', 101],
 ['aisle_id', 99],
 ['order_frequency', 98],
 ['user_preferred_day', 96],
 ['up_mean_order', 93],
 ['ua_first_order', 92],
 ['P01', 91],
 ['department_id', 88],
 ['ud_mean_order', 87],
 ['up_min_cart_position', 86],
 ['ua_last_order', 80],
 ['up_kurtosis_cart_position', 66],
 ['up_skewness_cart_position', 66],
 ['prod_preferred_time', 51],
 ['prod_prior_recency', 50],
 ['prod_orders', 46],
 ['ud_last_order', 41],
 ['prod_last_recency', 36],
 ['ud_first_order', 36],
 ['aisle_preferred_time', 30],
 ['P0', 25],
 ['P1', 23],
 ['aisle_preferred_day', 20],
 ['prod_preferred_day', 17]]

# for element in mayDeletedList:
train.drop(['user_id','order_id', 'product_id','user_total_products'],axis=1)
print("ok---------------------------------")
X = lgb.Dataset(train.drop(['user_id','order_id', 'product_id','user_total_products'],axis=1), label = reordered)
model = lgb.train(train_set=X, params=params, num_boost_round=500)

test["prob"] = model.predict(test.drop(['user_id','order_id', 'product_id','user_total_products'],axis=1))
test.to_csv("../test/"+"user_total_products"+".csv")
del test["prob"]


end = datetime.datetime.now()
print ("The time is ",(end - begin))

```

## Steps to reproduce
I am not sure How to reproduce , because  I did feature engineering for the dataset
1.
2.
3.

**Comment by guolinke** [comment]
refer to FAQ: https://github.com/Microsoft/LightGBM/blob/master/docs/FAQ.md#r-package

**Comment by yuan76316** [comment]
@guolinke  Thanks for the url. However, I still do not understand why I got AttributeError: module 'lightgbm' has no attribute 'Dataset'. Sorry for this newbie question, cloud you tell me why this happen? I just thought lgb.Dataset(train,label) is normal use of lgb. Did I miss something?

**Comment by guolinke** [comment]
@yuan76316 try ```lgb.unloader(wipe = TRUE)``` . It seems is a R's bug. 

@Laurae2 maybe we can add a clearer description for these strange R issues.

**Comment by Laurae2** [comment]
@guolinke The issue is LightGBM works with pointers and R is known to avoid using pointers, which is unfriendly when using LightGBM package as it requires rethinking how to work with pointers.

The issue is the same with data.table, which is unfriendly to any new users who never programmed using pointers. Any mistake by the end-user is punished immediately with unrecoverable issues (like overwriting the original data and not being able to recover the previous state of the data).

**Comment by guolinke** [comment]
@Laurae2 
Can we solve this inside our R-package ?

**Comment by Laurae2** [comment]
@guolinke Error happens here: https://github.com/Microsoft/LightGBM/blob/master/R-package/R/lgb.train.R#L156

```r
[LightGBM] [Fatal] Unknown parameter: aaaaaaaaaa
Error in lgb.call("LGBM_DatasetCreateFromCSC_R", ret = handle, private$raw_data@p,  : 
  api error: Unknown parameter: aaaaaaaaaa
```

Not sure how it can be fixed, without leading to a more serious crash. **Perhaps, work with a copied lgb.Dataset pointer and let the original one safe?**

Reproducible error:

```r
library(lightgbm)
data(agaricus.train, package = "lightgbm")
train <- agaricus.train
dtrain <- lgb.Dataset(train$data, label = train$label)
data(agaricus.test, package = "lightgbm")
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
params <- list(objective = "regression", metric = "l2")
valids <- list(test = dtest)
model <- lgb.train(params,
                   dtrain,
                   100,
                   valids,
                   min_data = 1,
                   learning_rate = 1,
                   early_stopping_rounds = 10,
                   aaaaaaaaaa = 1)

# On second run, it should stop at line 53
debugonce(lgb.train)
model <- lgb.train(params,
                   dtrain,
                   100,
                   valids,
                   min_data = 1,
                   learning_rate = 1,
                   early_stopping_rounds = 10)

# It happens also here
dtrain$construct()
dtest$construct()
```

Trying this workaround, it just crashes instead...:

```r
library(lightgbm)
data(agaricus.train, package = "lightgbm")
train <- agaricus.train
dtrain <- lgb.Dataset(train$data, label = train$label)
data(agaricus.test, package = "lightgbm")
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
params <- list(objective = "regression", metric = "l2")
valids <- list(test = dtest)

# Workaround...
dtrain$construct()
dtest$construct()

# CRASH
model <- lgb.train(params,
                   dtrain,
                   100,
                   valids,
                   min_data = 1,
                   learning_rate = 1,
                   early_stopping_rounds = 10,
                   aaaaaaaaaa = 1)
```

**Comment by yuan76316** [comment]
@guolinke , Sorry ,I used python to find this error.  Another strange thing is that When I call only
`import lightgbm as lgb` in jupyter
There is a strange error throw:
```
['user_id', 'product_id', 'up_orders', 'up_mean_day_since_last_purchase', 'up_sd_day_since_last_purchase', 'up_first_order', 'up_last_order', 'up_mean_order', 'up_sd_order', 'up_skewness_order', 'up_kurtosis_order', 'up_median_order', 'up_max_cart_position', 'up_average_cart_position', 'up_min_cart_position', 'up_sd_cart_position', 'up_skewness_cart_position', 'up_kurtosis_cart_position', 'up_median_cart_position', 'prod_preferred_day', 'prod_preferred_time', 'prod_users', 'prod_orders', 'prod_max_orders', 'prod_median_order_number', 'prod_prior_recency', 'prod_last_recency', 'prod_mean_add_to_cart_order', 'prod_mean_days_since_prior_order', 'prod_sd_days_since_prior_order', 'prod_sd_add_to_cart_order', 'order_frequency', 'aisle_id', 'department_id', 'prod_reorder_probability', 'prod_reorder_times', 'aisle_preferred_day', 'aisle_preferred_time', 'aisle_max_orders', 'aisle_mean_add_to_cart_order', 'aisle_mean_days_since_prior_order', 'aisle_sd_days_since_prior_order', 'aisle_reorder_ratio', 'department_sd_days_since_prior_order', 'user_total_products', 'user_period', 'user_mean_days_since_prior', 'user_max_days_since_prior', 'user_min_days_since_prior', 'user_sd_days_since_prior', 'user_skewness_days_since_prior', 'user_kurtosis_days_since_prior', 'user_orders_prod', 'usr_max_reorder', 'user_preferred_day', 'user_preferred_time', 'user_mode_department', 'user_mode_aisle', 'user_reorder_preffered_day_ratio', 'user_reorder_preffed_time_ratio', 'user_tenure', 'most_favorite_product', 'user_favorite_reorder_ratio', 'user_median_days_since_prior_order', 'user_second_orders', 'user_third_orders', 'user_meadian_order_numbers', 'user_prior_recency', 'user_last_recency', 'usr_second_reorder', 'usr_third_reorder', 'user_reoder_prior_recency', 'user_reorder_last_recency', 'user_reorder_ratio', 'user_distinct_products', 'user_reorder_weekend_ratio', 'user_reorder_noon_ratio', 'user_reorder_weekday_ratio', 'user_reorder_evening_ratio', 'user_mean_day', 'user_sd_day', 'user_skewness_day', 'user_kurtosis_day', 'user_mean_hour', 'user_median_hour', 'user_sd_hour', 'user_max_hour', 'user_min_hour', 'user_frequency_reorder', 'user_average_basket', 'order_id', 'eval_set', 'time_since_last_order', 'ua_orders', 'ua_reorders', 'ua_mean_day_since_last_purchase', 'ua_sd_day_since_last_purchase', 'ua_first_order', 'ua_last_order', 'ua_mean_order', 'ua_sd_order', 'ua_average_cart_position', 'ua_sd_cart_position', 'ud_orders', 'ud_reorders', 'ud_mean_day_since_last_purchase', 'ud_sd_day_since_last_purchase', 'ud_first_order', 'ud_last_order', 'ud_mean_order', 'ud_sd_order', 'ud_average_cart_position', 'ud_sd_cart_position', 'up_order_rate', 'up_orders_since_last_order', 'up_order_rate_since_first_order', 'reordered', 'Unnamed: 0_x', '0_x', '1_x', '2_x', '3_x', '4_x', '5_x', '6_x', '7_x', '8_x', '9_x', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', 'order_streak', 'P0', 'P00', 'P01', 'P1', 'P10', 'P11', '0_y', '1_y', '2_y', '3_y', '4_y', '5_y', '6_y', '7_y', '8_y', '9_y', 'cluster']
/root/instacart/code/lightgbm.py:60: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  train["reordered"] = train["reordered"].fillna(value=0)
(8474661,)
(8474661, 164)
(4833292, 164)
-----------------------------
up_median_cart_position
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-2ae3725bef24> in <module>()
----> 1 import lightgbm as lgb

/root/instacart/code/lightgbm.py in <module>()
    313 for element in mayDeletedList:
    314     print (element[0])
--> 315     X = lgb.Dataset(train.drop(['user_id','order_id', 'product_id',element[0]],axis=1), label = reordered,free_raw_data=False)
    316     model = lgb.train(train_set=X, params=params, num_boost_round=500)
    317 

AttributeError: module 'lightgbm' has no attribute 'Dataset'

```

Actually , I did not call any other functions

**Comment by guolinke** [comment]
@yuan76316 
can you try to install python-package from source ? 
```
git clone --recursive https://github.com/Microsoft/LightGBM
cd LightGBM/python-package
python setup.py install
```

**Comment by yuan76316** [comment]
@guolinke  Thanks,I will try it

**Comment by guolinke** [comment]
@Laurae2 
two solutions:
1. maybe we should have a new c_api named "CheckParameter". 
Before updating the parameters to Dataset in lgb.train, we should check the parameters first.

2. change the ```Dataset$update_param``` ( https://github.com/Microsoft/LightGBM/blob/6e07a8d5e3698dabd75a9dfa634b4a8f2eb52f1f/R-package/R/lgb.Dataset.R#L471-L477). Now it updates parameters from the lgb.train. We can use an additional field to save the parameters from lgb.train, and this additional field can be replaced.

**Comment by guolinke** [comment]
@wxchan 
It seems python also have this issues. 
I think Dataset should not remember the parameters from lgb.train

**Comment by wxchan** [comment]
@guolinke right. Should we make a copy of Dataset params before call lgb.train() and set it back after training?

**Comment by guolinke** [comment]
@Laurae2 
I found the crash is caused by this line: https://github.com/Microsoft/LightGBM/blob/master/R-package/R/utils.R#L45 

Do you know why ?

**Comment by guolinke** [comment]
@wxchan I think a simpler solution is using an additional param dict, which will be replaced every time call the lgb.train.

**Comment by Laurae2** [comment]
@guolinke I think the crash is not caused there, because it does not seem to cause any crash when I monitor the function with the debugger.

Try this:

```r
library(lightgbm)
data(agaricus.train, package = "lightgbm")
train <- agaricus.train
dtrain <- lgb.Dataset(train$data, label = train$label)
data(agaricus.test, package = "lightgbm")
test <- agaricus.test
dtest <- lgb.Dataset.create.valid(dtrain, test$data, label = test$label)
params <- list(objective = "regression", metric = "l2")
valids <- list(test = dtest)

# Workaround...
dtrain$construct()
dtest$construct()

# Prevent CRASH, make sure to not run everything but only line by line
debug(lgb.call)

# CRASH
model <- lgb.train(params,
                   dtrain,
                   100,
                   valids,
                   min_data = 1,
                   learning_rate = 1,
                   early_stopping_rounds = 10,
                   aaaaaaaaaa = 1)
```

**Comment by guolinke** [comment]
@Laurae2 
I am sure the crash is caused by that line.
you can try following to find this:
1. replace https://github.com/Microsoft/LightGBM/blob/master/R-package/R/utils.R#L43-L60 with ```stop("error")``` , you will find it doesn't crash.
2. replace https://github.com/Microsoft/LightGBM/blob/master/R-package/R/utils.R#L43-L60 with ```buf_len <- 200L; err_msg <- raw(buf_len); stop("error")``` , you will find it crashes.

**Comment by Laurae2** [comment]
@guolinke When I enter `lgb.call` (using my script) and immediately stops LightGBM (click stop in debugger), I can't close R anymore. However, if I run stuff in the Console, it works as expected.

Something strange is happening before `lgb.call` is called the first time and we have to find out what happens.

Reproducible example:

* Use RStudio
* Run my code
* Click immediately Stop at the first debugger prompt
* Try to close RStudio, and sees it does not close

If using default RGui: run my code, type `Q` to quit debugger, attempt to close RGui, and you get sent back to the debugger again for mysterious reasons. Type twice `Q` and it will eventually quit (LightGBM kept running even when stopped?).

**Comment by guolinke** [comment]
@Laurae2 I think it is some kind of memory manage error. I will investigate it. Let us discuss in another thread.

**Comment by ChristofHenkel** [comment]
Has this been fixed? I have the same issue on python 3.6. I installed using

```
git clone --recursive https://github.com/Microsoft/LightGBM
mkdir LightGBM/build
apt-get update
apt-get install --no-install-recommends nvidia-375
apt-get install --no-install-recommends nvidia-opencl-icd-375 nvidia-opencl-dev opencl-headers
apt-get install --no-install-recommends git cmake build-essential libboost-dev libboost-system-dev libboost-filesystem-dev
```

```cmake -DUSE_GPU=1 -DOpenCL_LIBRARY=../usr/lib/x86_64-linux-gnu/libOpenCL.so -DOpenCL_INCLUDE_DIR=../usr/lib/gcc/x86_64-linux-gnu/7/include LightGBM/build/.. & make -j4```

> -- OpenCL include directory:/usr/lib/gcc/x86_64-linux-gnu/7/include
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   filesystem
--   system
-- Configuring done
-- Generating done
-- Build files have been written to: /content
[ 49%] Built target lightgbm
[100%] Built target _lightgbm

```
apt-get -y install python-pip
pip install setuptools numpy scipy scikit-learn -U
cp /content/LightGBM/VERSION.txt /content/LightGBM/python-package/lightgbm/
cp /content/LightGBM/python-package/README.rst /content/
python ../content/LightGBM/python-package/setup.py install --precompile
```

> running install
> running build
> running install_egg_info
> running egg_info
> writing lightgbm.egg-info/PKG-INFO
> writing dependency_links to lightgbm.egg-info/dependency_links.txt
> writing requirements to lightgbm.egg-info/requires.txt
> writing top-level names to lightgbm.egg-info/top_level.txt
> reading manifest file 'lightgbm.egg-info/SOURCES.txt'
> writing manifest file 'lightgbm.egg-info/SOURCES.txt'
> removing '/usr/local/lib/python3.6/dist-packages/lightgbm-2.1.1-py3.6.egg-info' (and everything under it)
> Copying lightgbm.egg-info to /usr/local/lib/python3.6/dist-packages/lightgbm-2.1.1-py3.6.egg-info
> running install_scripts

**Comment by dotsonliu** [comment]
who know how to slove this problem?

**Comment by onozeam** [comment]
I suggest that you change the filename to other than `lightgbm.py`.
