### ISSUE TITLE
Tree model should contain num_leaves field

### ISSUE THREAD

**Issue by PPACI** [Microsoft/LightGBM#794]
Hi everyone, i got a strange bug in my jupyter notebook using LightGBM.
When trying to load data from a pandas Dataset, i got the following case :

## Environment info
Operating System: Ubuntu
Python: 3.5

## Error Message:
```
/opt/conda/lib/python3.5/site-packages/lightgbm/engine.py in train(params, train_set, num_boost_round, valid_sets, valid_names, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, evals_result, verbose_eval, learning_rates, keep_training_booster, callbacks)
    211         booster.best_score[dataset_name][eval_name] = score
    212     if not keep_training_booster:
--> 213         booster._load_model_from_string(booster._save_model_to_string())
    214         booster.free_dataset()
    215     return booster

/opt/conda/lib/python3.5/site-packages/lightgbm/basic.py in _load_model_from_string(self, model_str)
   1552             c_str(model_str),
   1553             ctypes.byref(out_num_iterations),
-> 1554             ctypes.byref(self.handle)))
   1555         out_num_class = ctypes.c_int(0)
   1556         _safe_call(_LIB.LGBM_BoosterGetNumClasses(

/opt/conda/lib/python3.5/site-packages/lightgbm/basic.py in _safe_call(ret)
     46     """
     47     if ret != 0:
---> 48         raise LightGBMError(_LIB.LGBM_GetLastError())
     49 
     50 

LightGBMError: b'Tree model should contain num_leaves field.'
```
## Reproducible examples
```python
data = pandas.read_csv('...')
label, data = data['XXX'], data.drop('XXX', axis=1)
train_data = lgb.Dataset(data=data, label=label)  # No error here
param = {
    'num_threads':4,
    'early_stopping_round':10,
    'feature_fraction':0.8,
    'num_leaves': 31,
}
bst = lgb.train(param, train_data, num_boost_round=100)
# This produce the given error.
```
Note that this example is perfectly working :
```python
train_data = lgb.Dataset(data=data.values, label=label)  # Using numpy array as input but pandas as label
param = {
    'num_threads':4,
    'early_stopping_round':10,
    'feature_fraction':0.8,
    'num_leaves': 31,
}
bst = lgb.train(param, train_data, num_boost_round=100)
```

**Comment by guolinke** [comment]
@wxchan it seems is some problem in python package.

**Comment by PPACI** [comment]
Note that i also tried several ways to install lightGBM  : pip, pip --no-binary, python setup.py from source but none worked.

**Comment by guolinke** [comment]
@PPACI can you provide the output log of first example ?

**Comment by PPACI** [comment]
Strangely, i couldn't have an output log in my jupyter notebook.
Even while configuring `logging.basicConfig(level=logging.DEBUG, stream=sys.stdout)`.
Also trying `verbose_eval=1` did not yield any log. Will investigate on my side to see if it's not a mis configuration of my jupyter. (other libs without problem in my setup)

**Comment by guolinke** [comment]
@PPACI 
The second example doesn't have logs as well ?

**Comment by PPACI** [comment]
Nothing. i will try i a non jupyter environnement and report.
I did test and the first example which doesn't work on last version, and it seems to work with release 2.0 from 3 may (tag d12e5e4).

**Comment by PPACI** [comment]
OK. Got no log in jupyter but it work in console.
```
[LightGBM] [Warning] Find whitespaces in feature_names, replace with underlines
[LightGBM] [Info] Total Bins 632
[LightGBM] [Info] Number of data: 55, number of used features: 83
[LightGBM] [Warning] Find whitespaces in feature_names, replace with underlines
[LightGBM] [Info] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Trained a tree with leaves=2 and max_depth=1
[LightGBM] [Info] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Trained a tree with leaves=2 and max_depth=1
[LightGBM] [Info] No further splits with positive gain, best gain: -inf
[LightGBM] [Info] Trained a tree with leaves=2 and max_depth=1
...
[LightGBM] [Info] Trained a tree with leaves=2 and max_depth=1
[LightGBM] [Fatal] Tree model should contain num_leaves field.
Traceback (most recent call last):
  File "test.py", line 53, in <module>
    bst = lgb.train(param, train_data, num_boost_round=100, verbose_eval=1, valid_sets=test_data)
  File "/opt/conda/lib/python3.5/site-packages/lightgbm/engine.py", line 213, in train
    booster._load_model_from_string(booster._save_model_to_string())
  File "/opt/conda/lib/python3.5/site-packages/lightgbm/basic.py", line 1554, in _load_model_from_string
    ctypes.byref(self.handle)))
  File "/opt/conda/lib/python3.5/site-packages/lightgbm/basic.py", line 48, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError())
lightgbm.basic.LightGBMError: b'Tree model should contain num_leaves field.'
```

**Comment by guolinke** [comment]
The problem is you are using very small data (55). you can try to set min_data=1 and min_data_in_bin=1 .

**Comment by PPACI** [comment]
For future reference : 
I had to set a higher **min_sum_hessian_in_leaf** (100 in my case) to have a working model.
Thank you guys to pointing me to training parameters in case of small data.
