### ISSUE TITLE
 python loadmodel error

### ISSUE THREAD

**Issue by hitfad** [Microsoft/LightGBM#892]
Traceback (most recent call last):
  File "loadmodel.py", line 8, in <module>
    bst = lgb.Booster(model_file='./LightGBM_model.txt')
  File "/root/anaconda2/lib/python2.7/site-packages/lightgbm-0.2-py2.7.egg/lightgbm/basic.py", line 1235, in __init__
    ctypes.byref(self.handle)))
  File "/root/anaconda2/lib/python2.7/site-packages/lightgbm-0.2-py2.7.egg/lightgbm/basic.py", line 47, in _safe_call
    raise LightGBMError(_LIB.LGBM_GetLastError())
lightgbm.basic.LightGBMError: Sigmoid parameter -1.000000 should be greater than zero

**Comment by guolinke** [comment]
@hitfad please use the latest version.
