### ISSUE TITLE
[python] windows build error

### ISSUE THREAD

**Issue by guolinke** [Microsoft/LightGBM#918]
@StrikerRUS 

after your PR of changing to use .sln file to build window python package. I met following error:

```
C:\Users\guoke\Documents\LightGBM\python-package>python setup.py install
running install
creating compile
creating compile\include
creating compile\include\LightGBM
copying ..\include\LightGBM\application.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\bin.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\boosting.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\config.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\c_api.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\dataset.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\dataset_loader.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\export.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\feature_group.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\lightgbm_R.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\meta.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\metric.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\network.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\objective_function.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\prediction_early_stop.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\R_object_helper.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\tree.h -> ./compile\include\LightGBM
copying ..\include\LightGBM\tree_learner.h -> ./compile\include\LightGBM
creating compile\include\LightGBM\utils
copying ..\include\LightGBM\utils\array_args.h -> ./compile\include\LightGBM\utils
copying ..\include\LightGBM\utils\common.h -> ./compile\include\LightGBM\utils
copying ..\include\LightGBM\utils\log.h -> ./compile\include\LightGBM\utils
copying ..\include\LightGBM\utils\openmp_wrapper.h -> ./compile\include\LightGBM\utils
copying ..\include\LightGBM\utils\pipeline_reader.h -> ./compile\include\LightGBM\utils
copying ..\include\LightGBM\utils\random.h -> ./compile\include\LightGBM\utils
copying ..\include\LightGBM\utils\text_reader.h -> ./compile\include\LightGBM\utils
copying ..\include\LightGBM\utils\threading.h -> ./compile\include\LightGBM\utils
creating compile\src
creating compile\src\application
copying ..\src\application\application.cpp -> ./compile\src\application
copying ..\src\application\predictor.hpp -> ./compile\src\application
creating compile\src\boosting
copying ..\src\boosting\boosting.cpp -> ./compile\src\boosting
copying ..\src\boosting\dart.hpp -> ./compile\src\boosting
copying ..\src\boosting\gbdt.cpp -> ./compile\src\boosting
copying ..\src\boosting\gbdt.h -> ./compile\src\boosting
copying ..\src\boosting\gbdt_model.cpp -> ./compile\src\boosting
copying ..\src\boosting\gbdt_prediction.cpp -> ./compile\src\boosting
copying ..\src\boosting\goss.hpp -> ./compile\src\boosting
copying ..\src\boosting\prediction_early_stop.cpp -> ./compile\src\boosting
copying ..\src\boosting\rf.hpp -> ./compile\src\boosting
copying ..\src\boosting\score_updater.hpp -> ./compile\src\boosting
copying ..\src\c_api.cpp -> ./compile\src
creating compile\src\io
copying ..\src\io\bin.cpp -> ./compile\src\io
copying ..\src\io\config.cpp -> ./compile\src\io
copying ..\src\io\dataset.cpp -> ./compile\src\io
copying ..\src\io\dataset_loader.cpp -> ./compile\src\io
copying ..\src\io\dense_bin.hpp -> ./compile\src\io
copying ..\src\io\dense_nbits_bin.hpp -> ./compile\src\io
copying ..\src\io\metadata.cpp -> ./compile\src\io
copying ..\src\io\ordered_sparse_bin.hpp -> ./compile\src\io
copying ..\src\io\parser.cpp -> ./compile\src\io
copying ..\src\io\parser.hpp -> ./compile\src\io
copying ..\src\io\sparse_bin.hpp -> ./compile\src\io
copying ..\src\io\tree.cpp -> ./compile\src\io
copying ..\src\lightgbm_R.cpp -> ./compile\src
copying ..\src\main.cpp -> ./compile\src
creating compile\src\metric
copying ..\src\metric\binary_metric.hpp -> ./compile\src\metric
copying ..\src\metric\dcg_calculator.cpp -> ./compile\src\metric
copying ..\src\metric\map_metric.hpp -> ./compile\src\metric
copying ..\src\metric\metric.cpp -> ./compile\src\metric
copying ..\src\metric\multiclass_metric.hpp -> ./compile\src\metric
copying ..\src\metric\rank_metric.hpp -> ./compile\src\metric
copying ..\src\metric\regression_metric.hpp -> ./compile\src\metric
copying ..\src\metric\xentropy_metric.hpp -> ./compile\src\metric
creating compile\src\network
copying ..\src\network\linkers.h -> ./compile\src\network
copying ..\src\network\linkers_mpi.cpp -> ./compile\src\network
copying ..\src\network\linkers_socket.cpp -> ./compile\src\network
copying ..\src\network\linker_topo.cpp -> ./compile\src\network
copying ..\src\network\network.cpp -> ./compile\src\network
copying ..\src\network\socket_wrapper.hpp -> ./compile\src\network
creating compile\src\objective
copying ..\src\objective\binary_objective.hpp -> ./compile\src\objective
copying ..\src\objective\multiclass_objective.hpp -> ./compile\src\objective
copying ..\src\objective\objective_function.cpp -> ./compile\src\objective
copying ..\src\objective\rank_objective.hpp -> ./compile\src\objective
copying ..\src\objective\regression_objective.hpp -> ./compile\src\objective
copying ..\src\objective\xentropy_objective.hpp -> ./compile\src\objective
creating compile\src\treelearner
copying ..\src\treelearner\data_parallel_tree_learner.cpp -> ./compile\src\treelearner
copying ..\src\treelearner\data_partition.hpp -> ./compile\src\treelearner
copying ..\src\treelearner\feature_histogram.hpp -> ./compile\src\treelearner
copying ..\src\treelearner\feature_parallel_tree_learner.cpp -> ./compile\src\treelearner
copying ..\src\treelearner\gpu_tree_learner.cpp -> ./compile\src\treelearner
copying ..\src\treelearner\gpu_tree_learner.h -> ./compile\src\treelearner
copying ..\src\treelearner\leaf_splits.hpp -> ./compile\src\treelearner
creating compile\src\treelearner\ocl
copying ..\src\treelearner\ocl\histogram16.cl -> ./compile\src\treelearner\ocl
copying ..\src\treelearner\ocl\histogram256.cl -> ./compile\src\treelearner\ocl
copying ..\src\treelearner\ocl\histogram64.cl -> ./compile\src\treelearner\ocl
copying ..\src\treelearner\parallel_tree_learner.h -> ./compile\src\treelearner
copying ..\src\treelearner\serial_tree_learner.cpp -> ./compile\src\treelearner
copying ..\src\treelearner\serial_tree_learner.h -> ./compile\src\treelearner
copying ..\src\treelearner\split_info.hpp -> ./compile\src\treelearner
copying ..\src\treelearner\tree_learner.cpp -> ./compile\src\treelearner
copying ..\src\treelearner\voting_parallel_tree_learner.cpp -> ./compile\src\treelearner
creating compile\windows
creating compile\windows\.vs
creating compile\windows\.vs\LightGBM
creating compile\windows\.vs\LightGBM\v15
copying ..\windows\.vs\LightGBM\v15\.suo -> ./compile\windows\.vs\LightGBM\v15
copying ..\windows\.vs\LightGBM\v15\Browse.VC.db -> ./compile\windows\.vs\LightGBM\v15
copying ..\windows\LightGBM.sln -> ./compile\windows
copying ..\windows\LightGBM.vcxproj -> ./compile\windows
copying ..\windows\LightGBM.vcxproj.filters -> ./compile\windows
copying ..\windows\LightGBM.vcxproj.user -> ./compile\windows
copying ..\windows\LightGBM_model.txt -> ./compile\windows
copying ..\windows\test.txt -> ./compile\windows
creating compile\windows\x64
creating compile\windows\x64\Debug
copying ..\windows\x64\Debug\application.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\bin.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\boosting.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\config.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\c_api.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\dataset.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\dataset_loader.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\data_parallel_tree_learner.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\dcg_calculator.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\feature_parallel_tree_learner.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\gbdt.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\gbdt_model.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\gbdt_prediction.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\lightgbm.exe -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\lightgbm.exp -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\lightgbm.ilk -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\lightgbm.lib -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\LightGBM.log -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\lightgbm.pdb -> ./compile\windows\x64\Debug
creating compile\windows\x64\Debug\LightGBM.tlog
copying ..\windows\x64\Debug\LightGBM.tlog\CL.command.1.tlog -> ./compile\windows\x64\Debug\LightGBM.tlog
copying ..\windows\x64\Debug\LightGBM.tlog\CL.read.1.tlog -> ./compile\windows\x64\Debug\LightGBM.tlog
copying ..\windows\x64\Debug\LightGBM.tlog\CL.write.1.tlog -> ./compile\windows\x64\Debug\LightGBM.tlog
copying ..\windows\x64\Debug\LightGBM.tlog\LightGBM.lastbuildstate -> ./compile\windows\x64\Debug\LightGBM.tlog
copying ..\windows\x64\Debug\LightGBM.tlog\LightGBM.write.1u.tlog -> ./compile\windows\x64\Debug\LightGBM.tlog
copying ..\windows\x64\Debug\LightGBM.tlog\link.command.1.tlog -> ./compile\windows\x64\Debug\LightGBM.tlog
copying ..\windows\x64\Debug\LightGBM.tlog\link.read.1.tlog -> ./compile\windows\x64\Debug\LightGBM.tlog
copying ..\windows\x64\Debug\LightGBM.tlog\link.write.1.tlog -> ./compile\windows\x64\Debug\LightGBM.tlog
copying ..\windows\x64\Debug\LightGBM_model.txt -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\lightgbm_R.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\linkers_mpi.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\linkers_socket.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\linker_topo.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\main.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\metadata.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\metric.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\network.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\objective_function.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\parser.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\prediction_early_stop.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\serial_tree_learner.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\test.txt -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\tree.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\tree_learner.obj -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\vc140.pdb -> ./compile\windows\x64\Debug
copying ..\windows\x64\Debug\voting_parallel_tree_learner.obj -> ./compile\windows\x64\Debug
copying ../CMakeLists.txt -> ./compile/
copying ../LICENSE -> ./
INFO:LightGBM:Starting to compile the library.
INFO:LightGBM:Starting to compile with MSBuild from existing solution file.
WARNING:LightGBM:Compilation with MSBuild from existing solution file failed.
INFO:LightGBM:Starting to compile with Visual Studio 15 2017 Win64.
INFO:LightGBM:Starting to compile with Visual Studio 14 2015 Win64.
INFO:LightGBM:Starting to compile with Visual Studio 12 2013 Win64.
Traceback (most recent call last):
  File "setup.py", line 229, in <module>
    'Topic :: Scientific/Engineering :: Artificial Intelligence'])
  File "C:\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 159, in run
    compile_cpp(use_mingw=self.mingw, use_gpu=self.gpu)
  File "setup.py", line 120, in compile_cpp
    raise Exception('Please install Visual Studio or MS Build first')
Exception: Please install Visual Studio or MS Build first

```

I installed vs2017 enterprise. I need to add its path to the $PATH$ to access MSBUILD ?

**Comment by StrikerRUS** [comment]
@guolinke Yes, MSBuild has it's own directory which should be added to the PATH. These lines indicate that there is no MSBuild in the PATH:
>INFO:LightGBM:Starting to compile with MSBuild from existing solution file.
WARNING:LightGBM:Compilation with MSBuild from existing solution file failed.

In my case (Windows 10  x64, VS 2013) it's `C:\Program Files (x86)\MSBuild\12.0\Bin`. 

After failure of compiling with MSBuild it tries to compile with CMake + VS, so CMake should be in the PATH (`C:\Program Files\CMake\bin`) and VS (`D:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin`).

**Comment by guolinke** [comment]
can we try to use sys.path.insert to insert some default folder and avoid the manully work?

**Comment by StrikerRUS** [comment]
I think yes. I'll create a PR soon.

**Comment by StrikerRUS** [comment]
@guolinke It's turned out that it is not so trivial task. As I understood, PATH changes on Windows have an effect only in case of setting `shell=True` which is strongly discouraged.
https://bugs.python.org/issue8557

I think that users understand they should modify PATH in case of using installed program from command line.

**Comment by guolinke** [comment]
@StrikerRUS 
Most user are not familiar with these PATH things, I don't think it is a good idea to leave it to user. 
And the path of msbuild.exe is also not easy to find if only installing visual studio ( ```C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin```, different version may have different path. ). And we often don't put it into PATH after installing visual studio.

solution:
1. rollback to cmake solution, but solve the local-language problem.
2. try to use ```msbuild.exe``` at first. if it failed, using ```C:\......\msbuild.exe``` to run.

refer to https://stackoverflow.com/questions/40694598/how-do-i-call-visual-studio-2017-rcs-version-of-msbuild-from-a-bat-file

**Comment by StrikerRUS** [comment]
@guolinke 
>rollback to cmake solution, but solve the local-language problem.

What is the point of it? The current version of `setup.py` rollbacks to cmake solution automatically when can't compile with MSBuild (e.g. not in the PATH).

**Comment by guolinke** [comment]
@StrikerRUS got it. I think this can be closed.

**Comment by StrikerRUS** [comment]
@guolinke OK. Anyway, I'll think about detecting installation directory of MSBuild.
