### ISSUE TITLE
docs build fail on python 2

### ISSUE THREAD

**Issue by sinianluoye** [Microsoft/LightGBM#996]
docs build fail on python 2
I repair it by change docs/conf.py line 30
from " from unittest.mock import Mock" to "from mock import Mock"
beceuse mock is a single model in python 2
i'm looking forward to someone can patch the tiny bug
thx.

## Environment info
Operating System: windows 10
CPU: intel core i7
C++/Python/R version:Python 2.7.13

## Error Message:

# Sphinx version: 1.6.4
# Python version: 2.7.13 (CPython)
# Docutils version: 0.14
# Jinja2 version: 2.9.6
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "c:\python27amd64\lib\site-packages\sphinx\cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "c:\python27amd64\lib\site-packages\sphinx\application.py", line 168, in __init__
    confoverrides or {}, self.tags)
  File "c:\python27amd64\lib\site-packages\sphinx\config.py", line 150, in __init__
    execfile_(filename, config)
  File "c:\python27amd64\lib\site-packages\sphinx\util\pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "c:\python27amd64\lib\site-packages\six.py", line 709, in exec_
    exec("""exec _code_ in _globs_, _locs_""")
  File "<string>", line 1, in <module>
  File "conf.py", line 30, in <module>
    from unittest.mock import Mock
ImportError: No module named mock
## Reproducible examples
```
cd docs
./make html
```
## Steps to reproduce
0. install python 2
1.  cd docs
2.  ./make html

**Comment by StrikerRUS** [comment]
Thank you very much for your report and for possible solution!
